In [1]:
def outer():
    print("Within outer function")
    def inner():
        print("Within inner function")
    print("Before calling inner")
    inner()
    print("After calling inner")

In [2]:
outer()

Within outer function
Before calling inner
Within inner function
After calling inner

In [3]:
def outer():
    print("Within outer function")
    def inner():
        print("Within inner function")
    return inner

In [4]:
funref1=outer()

Within outer function

In [5]:
funref1()

Within inner function

In [7]:
def outer():
    print('Within outer function')
    def raiseto(n):
        print("Finding square of",n)
        return n*n
    return raiseto

In [8]:
funref2=outer()

Within outer function

In [9]:
funref2(9)

Finding square of 9

81

In [1]:
def calculator(operation):
    def add(a,b):
        print('Addition')
        return a+b
    def sub(a,b):
        print('Sub')
        return a-b
    if operation=='add':
        return add
    else:
        return sub

In [2]:
funref3=calculator('add')

In [3]:
res=funref3(40,50)
print(res)

Addition
90

In [13]:
def decorator_func(some_func):
    def wrapper_func():
        print("Wrapper function started") #Pre processing before calling   
        some_func()    
        print("Wrapper function ended")  #Post processing after calling
    return wrapper_func 
    
def say_hello():
    print ("Hello")

a= decorator_func(say_hello)

a()

Wrapper function started
Hello
Wrapper function ended

In [4]:
def decorator_func(a):
    def wrapper_func(hello_var, world_var):
        hello = "Hello, "
        world = "World"    
        if not hello_var:
            hello_var = hello
        if not world_var:
            world_var = world
        return a(hello_var, world_var)  
    return wrapper_func

@decorator_func
def say_hello(hello_var, world_var):
    print(hello_var + " " + world_var)


say_hello("Hi","Welcome")

Hi Welcome

In [17]:
def decorator_func(a):
    def wrapper_func(hello_var=None, world_var=None):
        hello = "Hello, "
        world = "World"    
        if not hello_var:
            hello_var = hello
        if not world_var:
            world_var = world
        return a(hello_var, world_var)  
    return wrapper_func

@decorator_func
def say_hello(hello_var=None, world_var=None):
    print(hello_var + " " + world_var)


say_hello()

Hello,  World

In [6]:
def my_generator(n):

    # initialize counter
    value = 0

    # loop until counter is less than n
    while value < n:

        # produce the current value of the counter
        yield value

        # increment the counter
        value += 1

In [7]:
for i in my_generator(10):
    print(i)

0
1
2
3
4
5
6
7
8
9

In [20]:
generator = my_generator(3)

In [21]:
print(next(generator))

0

In [22]:
print(next(generator))

1

In [23]:
print(next(generator))

2

In [24]:
squares_generator = (i * i for i in range(5))

In [25]:
print(next(squares_generator))

0

In [26]:
print(next(squares_generator))

1

In [27]:
print(next(squares_generator))

4

In [33]:
def fibonacci_numbers(nums):
    x, y = 0, 1
    for _ in range(nums):
        x, y = y, x+y
        yield x

def square(nums):
    for num in nums:
        yield num**2

1

In [34]:
res = square(fibonacci_numbers(10))

In [35]:
next(res)

1

In [36]:
next(res)

1

In [37]:
next(res)

4

In [38]:
def optimizedreader(filepath):
    for line in open(filepath,'r'):
        yield line

In [39]:
oR=optimizedreader("C://data//iris.csv")

In [40]:
print(next(oR))

"sepal.length","sepal.width","petal.length","petal.width","variety"

In [41]:
print(next(oR))

5.1,3.5,1.4,.2,"Setosa"

In [45]:
readline=(line for line in open("C://data//iris.csv",'r'))

In [46]:
next(readline)

'"sepal.length","sepal.width","petal.length","petal.width","variety"\n'

In [47]:
with open("C://data//iris.csv",'r')  as op:
    for line in op:
        print(line)

"sepal.length","sepal.width","petal.length","petal.width","variety"

5.1,3.5,1.4,.2,"Setosa"

4.9,3,1.4,.2,"Setosa"

4.7,3.2,1.3,.2,"Setosa"

4.6,3.1,1.5,.2,"Setosa"

5,3.6,1.4,.2,"Setosa"

5.4,3.9,1.7,.4,"Setosa"

4.6,3.4,1.4,.3,"Setosa"

5,3.4,1.5,.2,"Setosa"

4.4,2.9,1.4,.2,"Setosa"

4.9,3.1,1.5,.1,"Setosa"

5.4,3.7,1.5,.2,"Setosa"

4.8,3.4,1.6,.2,"Setosa"

4.8,3,1.4,.1,"Setosa"

4.3,3,1.1,.1,"Setosa"

5.8,4,1.2,.2,"Setosa"

5.7,4.4,1.5,.4,"Setosa"

5.4,3.9,1.3,.4,"Setosa"

5.1,3.5,1.4,.3,"Setosa"

5.7,3.8,1.7,.3,"Setosa"

5.1,3.8,1.5,.3,"Setosa"

5.4,3.4,1.7,.2,"Setosa"

5.1,3.7,1.5,.4,"Setosa"

4.6,3.6,1,.2,"Setosa"

5.1,3.3,1.7,.5,"Setosa"

4.8,3.4,1.9,.2,"Setosa"

5,3,1.6,.2,"Setosa"

5,3.4,1.6,.4,"Setosa"

5.2,3.5,1.5,.2,"Setosa"

5.2,3.4,1.4,.2,"Setosa"

4.7,3.2,1.6,.2,"Setosa"

4.8,3.1,1.6,.2,"Setosa"

5.4,3.4,1.5,.4,"Setosa"

5.2,4.1,1.5,.1,"Setosa"

5.5,4.2,1.4,.2,"Setosa"

4.9,3.1,1.5,.2,"Setosa"

5,3.2,1.2,.2,"Setosa"

5.5,3.5,1.3,.2,"Setosa"

4.9,3.6,1.4,.1,"Setosa"

4.4,3,1.3,.2,"Setosa"

5.1,3.4,1.5,.2,"Setosa"

5,3.5,1.3,.3,"Setosa"

4.5,2.3,1.3,.3,"Setosa"

4.4,3.2,1.3,.2,"Setosa"

5,3.5,1.6,.6,"Setosa"

5.1,3.8,1.9,.4,"Setosa"

4.8,3,1.4,.3,"Setosa"

5.1,3.8,1.6,.2,"Setosa"

4.6,3.2,1.4,.2,"Setosa"

5.3,3.7,1.5,.2,"Setosa"

5,3.3,1.4,.2,"Setosa"

7,3.2,4.7,1.4,"Versicolor"

6.4,3.2,4.5,1.5,"Versicolor"

6.9,3.1,4.9,1.5,"Versicolor"

5.5,2.3,4,1.3,"Versicolor"

6.5,2.8,4.6,1.5,"Versicolor"

5.7,2.8,4.5,1.3,"Versicolor"

6.3,3.3,4.7,1.6,"Versicolor"

4.9,2.4,3.3,1,"Versicolor"

6.6,2.9,4.6,1.3,"Versicolor"

5.2,2.7,3.9,1.4,"Versicolor"

5,2,3.5,1,"Versicolor"

5.9,3,4.2,1.5,"Versicolor"

6,2.2,4,1,"Versicolor"

6.1,2.9,4.7,1.4,"Versicolor"

5.6,2.9,3.6,1.3,"Versicolor"

6.7,3.1,4.4,1.4,"Versicolor"

5.6,3,4.5,1.5,"Versicolor"

5.8,2.7,4.1,1,"Versicolor"

6.2,2.2,4.5,1.5,"Versicolor"

5.6,2.5,3.9,1.1,"Versicolor"

5.9,3.2,4.8,1.8,"Versicolor"

6.1,2.8,4,1.3,"Versicolor"

6.3,2.5,4.9,1.5,"Versicolor"

6.1,2.8,4.7,1.2,"Versicolor"

6.4,2.9,4.3,1.3,"Versicolor"

6.6,3,4.4,1.4,"Versicolor"

6.8,2.8,4.8,1.4,"Versicolor"

6.7,3,5,1.7,"Versicolor"

6,2.9,4.5,1.5,"Versicolor"

5.7,2.6,3.5,1,"Versicolor"

5.5,2.4,3.8,1.1,"Versicolor"

5.5,2.4,3.7,1,"Versicolor"

5.8,2.7,3.9,1.2,"Versicolor"

6,2.7,5.1,1.6,"Versicolor"

5.4,3,4.5,1.5,"Versicolor"

6,3.4,4.5,1.6,"Versicolor"

6.7,3.1,4.7,1.5,"Versicolor"

6.3,2.3,4.4,1.3,"Versicolor"

5.6,3,4.1,1.3,"Versicolor"

5.5,2.5,4,1.3,"Versicolor"

5.5,2.6,4.4,1.2,"Versicolor"

6.1,3,4.6,1.4,"Versicolor"

5.8,2.6,4,1.2,"Versicolor"

5,2.3,3.3,1,"Versicolor"

5.6,2.7,4.2,1.3,"Versicolor"

5.7,3,4.2,1.2,"Versicolor"

5.7,2.9,4.2,1.3,"Versicolor"

6.2,2.9,4.3,1.3,"Versicolor"

5.1,2.5,3,1.1,"Versicolor"

5.7,2.8,4.1,1.3,"Versicolor"

6.3,3.3,6,2.5,"Virginica"

5.8,2.7,5.1,1.9,"Virginica"

7.1,3,5.9,2.1,"Virginica"

6.3,2.9,5.6,1.8,"Virginica"

6.5,3,5.8,2.2,"Virginica"

7.6,3,6.6,2.1,"Virginica"

4.9,2.5,4.5,1.7,"Virginica"

7.3,2.9,6.3,1.8,"Virginica"

6.7,2.5,5.8,1.8,"Virginica"

7.2,3.6,6.1,2.5,"Virginica"

6.5,3.2,5.1,2,"Virginica"

6.4,2.7,5.3,1.9,"Virginica"

6.8,3,5.5,2.1,"Virginica"

5.7,2.5,5,2,"Virginica"

5.8,2.8,5.1,2.4,"Virginica"

6.4,3.2,5.3,2.3,"Virginica"

6.5,3,5.5,1.8,"Virginica"

7.7,3.8,6.7,2.2,"Virginica"

7.7,2.6,6.9,2.3,"Virginica"

6,2.2,5,1.5,"Virginica"

6.9,3.2,5.7,2.3,"Virginica"

5.6,2.8,4.9,2,"Virginica"

7.7,2.8,6.7,2,"Virginica"

6.3,2.7,4.9,1.8,"Virginica"

6.7,3.3,5.7,2.1,"Virginica"

7.2,3.2,6,1.8,"Virginica"

6.2,2.8,4.8,1.8,"Virginica"

6.1,3,4.9,1.8,"Virginica"

6.4,2.8,5.6,2.1,"Virginica"

7.2,3,5.8,1.6,"Virginica"

7.4,2.8,6.1,1.9,"Virginica"

7.9,3.8,6.4,2,"Virginica"

6.4,2.8,5.6,2.2,"Virginica"

6.3,2.8,5.1,1.5,"Virginica"

6.1,2.6,5.6,1.4,"Virginica"

7.7,3,6.1,2.3,"Virginica"

6.3,3.4,5.6,2.4,"Virginica"

6.4,3.1,5.5,1.8,"Virginica"

6,3,4.8,1.8,"Virginica"

6.9,3.1,5.4,2.1,"Virginica"

6.7,3.1,5.6,2.4,"Virginica"

6.9,3.1,5.1,2.3,"Virginica"

5.8,2.7,5.1,1.9,"Virginica"

6.8,3.2,5.9,2.3,"Virginica"

6.7,3.3,5.7,2.5,"Virginica"

6.7,3,5.2,2.3,"Virginica"

6.3,2.5,5,1.9,"Virginica"

6.5,3,5.2,2,"Virginica"

6.2,3.4,5.4,2.3,"Virginica"

5.9,3,5.1,1.8,"Virginica"

In [48]:
import csv

In [58]:
reader=csv.DictReader(open("C://data//iris.csv",'r'))

In [59]:
for data in reader:
    print(data)

{'sepal.length': '5.1', 'sepal.width': '3.5', 'petal.length': '1.4', 'petal.width': '.2', 'variety': 'Setosa'}
{'sepal.length': '4.9', 'sepal.width': '3', 'petal.length': '1.4', 'petal.width': '.2', 'variety': 'Setosa'}
{'sepal.length': '4.7', 'sepal.width': '3.2', 'petal.length': '1.3', 'petal.width': '.2', 'variety': 'Setosa'}
{'sepal.length': '4.6', 'sepal.width': '3.1', 'petal.length': '1.5', 'petal.width': '.2', 'variety': 'Setosa'}
{'sepal.length': '5', 'sepal.width': '3.6', 'petal.length': '1.4', 'petal.width': '.2', 'variety': 'Setosa'}
{'sepal.length': '5.4', 'sepal.width': '3.9', 'petal.length': '1.7', 'petal.width': '.4', 'variety': 'Setosa'}
{'sepal.length': '4.6', 'sepal.width': '3.4', 'petal.length': '1.4', 'petal.width': '.3', 'variety': 'Setosa'}
{'sepal.length': '5', 'sepal.width': '3.4', 'petal.length': '1.5', 'petal.width': '.2', 'variety': 'Setosa'}
{'sepal.length': '4.4', 'sepal.width': '2.9', 'petal.length': '1.4', 'petal.width': '.2', 'variety': 'Setosa'}
{'sepal.length': '4.9', 'sepal.width': '3.1', 'petal.length': '1.5', 'petal.width': '.1', 'variety': 'Setosa'}
{'sepal.length': '5.4', 'sepal.width': '3.7', 'petal.length': '1.5', 'petal.width': '.2', 'variety': 'Setosa'}
{'sepal.length': '4.8', 'sepal.width': '3.4', 'petal.length': '1.6', 'petal.width': '.2', 'variety': 'Setosa'}
{'sepal.length': '4.8', 'sepal.width': '3', 'petal.length': '1.4', 'petal.width': '.1', 'variety': 'Setosa'}
{'sepal.length': '4.3', 'sepal.width': '3', 'petal.length': '1.1', 'petal.width': '.1', 'variety': 'Setosa'}
{'sepal.length': '5.8', 'sepal.width': '4', 'petal.length': '1.2', 'petal.width': '.2', 'variety': 'Setosa'}
{'sepal.length': '5.7', 'sepal.width': '4.4', 'petal.length': '1.5', 'petal.width': '.4', 'variety': 'Setosa'}
{'sepal.length': '5.4', 'sepal.width': '3.9', 'petal.length': '1.3', 'petal.width': '.4', 'variety': 'Setosa'}
{'sepal.length': '5.1', 'sepal.width': '3.5', 'petal.length': '1.4', 'petal.width': '.3', 'variety': 'Setosa'}
{'sepal.length': '5.7', 'sepal.width': '3.8', 'petal.length': '1.7', 'petal.width': '.3', 'variety': 'Setosa'}
{'sepal.length': '5.1', 'sepal.width': '3.8', 'petal.length': '1.5', 'petal.width': '.3', 'variety': 'Setosa'}
{'sepal.length': '5.4', 'sepal.width': '3.4', 'petal.length': '1.7', 'petal.width': '.2', 'variety': 'Setosa'}
{'sepal.length': '5.1', 'sepal.width': '3.7', 'petal.length': '1.5', 'petal.width': '.4', 'variety': 'Setosa'}
{'sepal.length': '4.6', 'sepal.width': '3.6', 'petal.length': '1', 'petal.width': '.2', 'variety': 'Setosa'}
{'sepal.length': '5.1', 'sepal.width': '3.3', 'petal.length': '1.7', 'petal.width': '.5', 'variety': 'Setosa'}
{'sepal.length': '4.8', 'sepal.width': '3.4', 'petal.length': '1.9', 'petal.width': '.2', 'variety': 'Setosa'}
{'sepal.length': '5', 'sepal.width': '3', 'petal.length': '1.6', 'petal.width': '.2', 'variety': 'Setosa'}
{'sepal.length': '5', 'sepal.width': '3.4', 'petal.length': '1.6', 'petal.width': '.4', 'variety': 'Setosa'}
{'sepal.length': '5.2', 'sepal.width': '3.5', 'petal.length': '1.5', 'petal.width': '.2', 'variety': 'Setosa'}
{'sepal.length': '5.2', 'sepal.width': '3.4', 'petal.length': '1.4', 'petal.width': '.2', 'variety': 'Setosa'}
{'sepal.length': '4.7', 'sepal.width': '3.2', 'petal.length': '1.6', 'petal.width': '.2', 'variety': 'Setosa'}
{'sepal.length': '4.8', 'sepal.width': '3.1', 'petal.length': '1.6', 'petal.width': '.2', 'variety': 'Setosa'}
{'sepal.length': '5.4', 'sepal.width': '3.4', 'petal.length': '1.5', 'petal.width': '.4', 'variety': 'Setosa'}
{'sepal.length': '5.2', 'sepal.width': '4.1', 'petal.length': '1.5', 'petal.width': '.1', 'variety': 'Setosa'}
{'sepal.length': '5.5', 'sepal.width': '4.2', 'petal.length': '1.4', 'petal.width': '.2', 'variety': 'Setosa'}
{'sepal.length': '4.9', 'sepal.width': '3.1', 'petal.length': '1.5', 'petal.width': '.2', 'variety': 'Setosa'}
{'sepal.length': '5', 'sepal.width': '3.2', 'petal.length': '1.2', 'petal.width': '.2', 'variety': 'Setosa'}
{'sepal.length': '5.5', 'sepal.width': '3.5', 'petal.length': '1.3', 'petal.width': '.2', 'variety': 'Setosa'}
{'sepal.length': '4.9', 'sepal.width': '3.6', 'petal.length': '1.4', 'petal.width': '.1', 'variety': 'Setosa'}
{'sepal.length': '4.4', 'sepal.width': '3', 'petal.length': '1.3', 'petal.width': '.2', 'variety': 'Setosa'}
{'sepal.length': '5.1', 'sepal.width': '3.4', 'petal.length': '1.5', 'petal.width': '.2', 'variety': 'Setosa'}
{'sepal.length': '5', 'sepal.width': '3.5', 'petal.length': '1.3', 'petal.width': '.3', 'variety': 'Setosa'}
{'sepal.length': '4.5', 'sepal.width': '2.3', 'petal.length': '1.3', 'petal.width': '.3', 'variety': 'Setosa'}
{'sepal.length': '4.4', 'sepal.width': '3.2', 'petal.length': '1.3', 'petal.width': '.2', 'variety': 'Setosa'}
{'sepal.length': '5', 'sepal.width': '3.5', 'petal.length': '1.6', 'petal.width': '.6', 'variety': 'Setosa'}
{'sepal.length': '5.1', 'sepal.width': '3.8', 'petal.length': '1.9', 'petal.width': '.4', 'variety': 'Setosa'}
{'sepal.length': '4.8', 'sepal.width': '3', 'petal.length': '1.4', 'petal.width': '.3', 'variety': 'Setosa'}
{'sepal.length': '5.1', 'sepal.width': '3.8', 'petal.length': '1.6', 'petal.width': '.2', 'variety': 'Setosa'}
{'sepal.length': '4.6', 'sepal.width': '3.2', 'petal.length': '1.4', 'petal.width': '.2', 'variety': 'Setosa'}
{'sepal.length': '5.3', 'sepal.width': '3.7', 'petal.length': '1.5', 'petal.width': '.2', 'variety': 'Setosa'}
{'sepal.length': '5', 'sepal.width': '3.3', 'petal.length': '1.4', 'petal.width': '.2', 'variety': 'Setosa'}
{'sepal.length': '7', 'sepal.width': '3.2', 'petal.length': '4.7', 'petal.width': '1.4', 'variety': 'Versicolor'}
{'sepal.length': '6.4', 'sepal.width': '3.2', 'petal.length': '4.5', 'petal.width': '1.5', 'variety': 'Versicolor'}
{'sepal.length': '6.9', 'sepal.width': '3.1', 'petal.length': '4.9', 'petal.width': '1.5', 'variety': 'Versicolor'}
{'sepal.length': '5.5', 'sepal.width': '2.3', 'petal.length': '4', 'petal.width': '1.3', 'variety': 'Versicolor'}
{'sepal.length': '6.5', 'sepal.width': '2.8', 'petal.length': '4.6', 'petal.width': '1.5', 'variety': 'Versicolor'}
{'sepal.length': '5.7', 'sepal.width': '2.8', 'petal.length': '4.5', 'petal.width': '1.3', 'variety': 'Versicolor'}
{'sepal.length': '6.3', 'sepal.width': '3.3', 'petal.length': '4.7', 'petal.width': '1.6', 'variety': 'Versicolor'}
{'sepal.length': '4.9', 'sepal.width': '2.4', 'petal.length': '3.3', 'petal.width': '1', 'variety': 'Versicolor'}
{'sepal.length': '6.6', 'sepal.width': '2.9', 'petal.length': '4.6', 'petal.width': '1.3', 'variety': 'Versicolor'}
{'sepal.length': '5.2', 'sepal.width': '2.7', 'petal.length': '3.9', 'petal.width': '1.4', 'variety': 'Versicolor'}
{'sepal.length': '5', 'sepal.width': '2', 'petal.length': '3.5', 'petal.width': '1', 'variety': 'Versicolor'}
{'sepal.length': '5.9', 'sepal.width': '3', 'petal.length': '4.2', 'petal.width': '1.5', 'variety': 'Versicolor'}
{'sepal.length': '6', 'sepal.width': '2.2', 'petal.length': '4', 'petal.width': '1', 'variety': 'Versicolor'}
{'sepal.length': '6.1', 'sepal.width': '2.9', 'petal.length': '4.7', 'petal.width': '1.4', 'variety': 'Versicolor'}
{'sepal.length': '5.6', 'sepal.width': '2.9', 'petal.length': '3.6', 'petal.width': '1.3', 'variety': 'Versicolor'}
{'sepal.length': '6.7', 'sepal.width': '3.1', 'petal.length': '4.4', 'petal.width': '1.4', 'variety': 'Versicolor'}
{'sepal.length': '5.6', 'sepal.width': '3', 'petal.length': '4.5', 'petal.width': '1.5', 'variety': 'Versicolor'}
{'sepal.length': '5.8', 'sepal.width': '2.7', 'petal.length': '4.1', 'petal.width': '1', 'variety': 'Versicolor'}
{'sepal.length': '6.2', 'sepal.width': '2.2', 'petal.length': '4.5', 'petal.width': '1.5', 'variety': 'Versicolor'}
{'sepal.length': '5.6', 'sepal.width': '2.5', 'petal.length': '3.9', 'petal.width': '1.1', 'variety': 'Versicolor'}
{'sepal.length': '5.9', 'sepal.width': '3.2', 'petal.length': '4.8', 'petal.width': '1.8', 'variety': 'Versicolor'}
{'sepal.length': '6.1', 'sepal.width': '2.8', 'petal.length': '4', 'petal.width': '1.3', 'variety': 'Versicolor'}
{'sepal.length': '6.3', 'sepal.width': '2.5', 'petal.length': '4.9', 'petal.width': '1.5', 'variety': 'Versicolor'}
{'sepal.length': '6.1', 'sepal.width': '2.8', 'petal.length': '4.7', 'petal.width': '1.2', 'variety': 'Versicolor'}
{'sepal.length': '6.4', 'sepal.width': '2.9', 'petal.length': '4.3', 'petal.width': '1.3', 'variety': 'Versicolor'}
{'sepal.length': '6.6', 'sepal.width': '3', 'petal.length': '4.4', 'petal.width': '1.4', 'variety': 'Versicolor'}
{'sepal.length': '6.8', 'sepal.width': '2.8', 'petal.length': '4.8', 'petal.width': '1.4', 'variety': 'Versicolor'}
{'sepal.length': '6.7', 'sepal.width': '3', 'petal.length': '5', 'petal.width': '1.7', 'variety': 'Versicolor'}
{'sepal.length': '6', 'sepal.width': '2.9', 'petal.length': '4.5', 'petal.width': '1.5', 'variety': 'Versicolor'}
{'sepal.length': '5.7', 'sepal.width': '2.6', 'petal.length': '3.5', 'petal.width': '1', 'variety': 'Versicolor'}
{'sepal.length': '5.5', 'sepal.width': '2.4', 'petal.length': '3.8', 'petal.width': '1.1', 'variety': 'Versicolor'}
{'sepal.length': '5.5', 'sepal.width': '2.4', 'petal.length': '3.7', 'petal.width': '1', 'variety': 'Versicolor'}
{'sepal.length': '5.8', 'sepal.width': '2.7', 'petal.length': '3.9', 'petal.width': '1.2', 'variety': 'Versicolor'}
{'sepal.length': '6', 'sepal.width': '2.7', 'petal.length': '5.1', 'petal.width': '1.6', 'variety': 'Versicolor'}
{'sepal.length': '5.4', 'sepal.width': '3', 'petal.length': '4.5', 'petal.width': '1.5', 'variety': 'Versicolor'}
{'sepal.length': '6', 'sepal.width': '3.4', 'petal.length': '4.5', 'petal.width': '1.6', 'variety': 'Versicolor'}
{'sepal.length': '6.7', 'sepal.width': '3.1', 'petal.length': '4.7', 'petal.width': '1.5', 'variety': 'Versicolor'}
{'sepal.length': '6.3', 'sepal.width': '2.3', 'petal.length': '4.4', 'petal.width': '1.3', 'variety': 'Versicolor'}
{'sepal.length': '5.6', 'sepal.width': '3', 'petal.length': '4.1', 'petal.width': '1.3', 'variety': 'Versicolor'}
{'sepal.length': '5.5', 'sepal.width': '2.5', 'petal.length': '4', 'petal.width': '1.3', 'variety': 'Versicolor'}
{'sepal.length': '5.5', 'sepal.width': '2.6', 'petal.length': '4.4', 'petal.width': '1.2', 'variety': 'Versicolor'}
{'sepal.length': '6.1', 'sepal.width': '3', 'petal.length': '4.6', 'petal.width': '1.4', 'variety': 'Versicolor'}
{'sepal.length': '5.8', 'sepal.width': '2.6', 'petal.length': '4', 'petal.width': '1.2', 'variety': 'Versicolor'}
{'sepal.length': '5', 'sepal.width': '2.3', 'petal.length': '3.3', 'petal.width': '1', 'variety': 'Versicolor'}
{'sepal.length': '5.6', 'sepal.width': '2.7', 'petal.length': '4.2', 'petal.width': '1.3', 'variety': 'Versicolor'}
{'sepal.length': '5.7', 'sepal.width': '3', 'petal.length': '4.2', 'petal.width': '1.2', 'variety': 'Versicolor'}
{'sepal.length': '5.7', 'sepal.width': '2.9', 'petal.length': '4.2', 'petal.width': '1.3', 'variety': 'Versicolor'}
{'sepal.length': '6.2', 'sepal.width': '2.9', 'petal.length': '4.3', 'petal.width': '1.3', 'variety': 'Versicolor'}
{'sepal.length': '5.1', 'sepal.width': '2.5', 'petal.length': '3', 'petal.width': '1.1', 'variety': 'Versicolor'}
{'sepal.length': '5.7', 'sepal.width': '2.8', 'petal.length': '4.1', 'petal.width': '1.3', 'variety': 'Versicolor'}
{'sepal.length': '6.3', 'sepal.width': '3.3', 'petal.length': '6', 'petal.width': '2.5', 'variety': 'Virginica'}
{'sepal.length': '5.8', 'sepal.width': '2.7', 'petal.length': '5.1', 'petal.width': '1.9', 'variety': 'Virginica'}
{'sepal.length': '7.1', 'sepal.width': '3', 'petal.length': '5.9', 'petal.width': '2.1', 'variety': 'Virginica'}
{'sepal.length': '6.3', 'sepal.width': '2.9', 'petal.length': '5.6', 'petal.width': '1.8', 'variety': 'Virginica'}
{'sepal.length': '6.5', 'sepal.width': '3', 'petal.length': '5.8', 'petal.width': '2.2', 'variety': 'Virginica'}
{'sepal.length': '7.6', 'sepal.width': '3', 'petal.length': '6.6', 'petal.width': '2.1', 'variety': 'Virginica'}
{'sepal.length': '4.9', 'sepal.width': '2.5', 'petal.length': '4.5', 'petal.width': '1.7', 'variety': 'Virginica'}
{'sepal.length': '7.3', 'sepal.width': '2.9', 'petal.length': '6.3', 'petal.width': '1.8', 'variety': 'Virginica'}
{'sepal.length': '6.7', 'sepal.width': '2.5', 'petal.length': '5.8', 'petal.width': '1.8', 'variety': 'Virginica'}
{'sepal.length': '7.2', 'sepal.width': '3.6', 'petal.length': '6.1', 'petal.width': '2.5', 'variety': 'Virginica'}
{'sepal.length': '6.5', 'sepal.width': '3.2', 'petal.length': '5.1', 'petal.width': '2', 'variety': 'Virginica'}
{'sepal.length': '6.4', 'sepal.width': '2.7', 'petal.length': '5.3', 'petal.width': '1.9', 'variety': 'Virginica'}
{'sepal.length': '6.8', 'sepal.width': '3', 'petal.length': '5.5', 'petal.width': '2.1', 'variety': 'Virginica'}
{'sepal.length': '5.7', 'sepal.width': '2.5', 'petal.length': '5', 'petal.width': '2', 'variety': 'Virginica'}
{'sepal.length': '5.8', 'sepal.width': '2.8', 'petal.length': '5.1', 'petal.width': '2.4', 'variety': 'Virginica'}
{'sepal.length': '6.4', 'sepal.width': '3.2', 'petal.length': '5.3', 'petal.width': '2.3', 'variety': 'Virginica'}
{'sepal.length': '6.5', 'sepal.width': '3', 'petal.length': '5.5', 'petal.width': '1.8', 'variety': 'Virginica'}
{'sepal.length': '7.7', 'sepal.width': '3.8', 'petal.length': '6.7', 'petal.width': '2.2', 'variety': 'Virginica'}
{'sepal.length': '7.7', 'sepal.width': '2.6', 'petal.length': '6.9', 'petal.width': '2.3', 'variety': 'Virginica'}
{'sepal.length': '6', 'sepal.width': '2.2', 'petal.length': '5', 'petal.width': '1.5', 'variety': 'Virginica'}
{'sepal.length': '6.9', 'sepal.width': '3.2', 'petal.length': '5.7', 'petal.width': '2.3', 'variety': 'Virginica'}
{'sepal.length': '5.6', 'sepal.width': '2.8', 'petal.length': '4.9', 'petal.width': '2', 'variety': 'Virginica'}
{'sepal.length': '7.7', 'sepal.width': '2.8', 'petal.length': '6.7', 'petal.width': '2', 'variety': 'Virginica'}
{'sepal.length': '6.3', 'sepal.width': '2.7', 'petal.length': '4.9', 'petal.width': '1.8', 'variety': 'Virginica'}
{'sepal.length': '6.7', 'sepal.width': '3.3', 'petal.length': '5.7', 'petal.width': '2.1', 'variety': 'Virginica'}
{'sepal.length': '7.2', 'sepal.width': '3.2', 'petal.length': '6', 'petal.width': '1.8', 'variety': 'Virginica'}
{'sepal.length': '6.2', 'sepal.width': '2.8', 'petal.length': '4.8', 'petal.width': '1.8', 'variety': 'Virginica'}
{'sepal.length': '6.1', 'sepal.width': '3', 'petal.length': '4.9', 'petal.width': '1.8', 'variety': 'Virginica'}
{'sepal.length': '6.4', 'sepal.width': '2.8', 'petal.length': '5.6', 'petal.width': '2.1', 'variety': 'Virginica'}
{'sepal.length': '7.2', 'sepal.width': '3', 'petal.length': '5.8', 'petal.width': '1.6', 'variety': 'Virginica'}
{'sepal.length': '7.4', 'sepal.width': '2.8', 'petal.length': '6.1', 'petal.width': '1.9', 'variety': 'Virginica'}
{'sepal.length': '7.9', 'sepal.width': '3.8', 'petal.length': '6.4', 'petal.width': '2', 'variety': 'Virginica'}
{'sepal.length': '6.4', 'sepal.width': '2.8', 'petal.length': '5.6', 'petal.width': '2.2', 'variety': 'Virginica'}
{'sepal.length': '6.3', 'sepal.width': '2.8', 'petal.length': '5.1', 'petal.width': '1.5', 'variety': 'Virginica'}
{'sepal.length': '6.1', 'sepal.width': '2.6', 'petal.length': '5.6', 'petal.width': '1.4', 'variety': 'Virginica'}
{'sepal.length': '7.7', 'sepal.width': '3', 'petal.length': '6.1', 'petal.width': '2.3', 'variety': 'Virginica'}
{'sepal.length': '6.3', 'sepal.width': '3.4', 'petal.length': '5.6', 'petal.width': '2.4', 'variety': 'Virginica'}
{'sepal.length': '6.4', 'sepal.width': '3.1', 'petal.length': '5.5', 'petal.width': '1.8', 'variety': 'Virginica'}
{'sepal.length': '6', 'sepal.width': '3', 'petal.length': '4.8', 'petal.width': '1.8', 'variety': 'Virginica'}
{'sepal.length': '6.9', 'sepal.width': '3.1', 'petal.length': '5.4', 'petal.width': '2.1', 'variety': 'Virginica'}
{'sepal.length': '6.7', 'sepal.width': '3.1', 'petal.length': '5.6', 'petal.width': '2.4', 'variety': 'Virginica'}
{'sepal.length': '6.9', 'sepal.width': '3.1', 'petal.length': '5.1', 'petal.width': '2.3', 'variety': 'Virginica'}
{'sepal.length': '5.8', 'sepal.width': '2.7', 'petal.length': '5.1', 'petal.width': '1.9', 'variety': 'Virginica'}
{'sepal.length': '6.8', 'sepal.width': '3.2', 'petal.length': '5.9', 'petal.width': '2.3', 'variety': 'Virginica'}
{'sepal.length': '6.7', 'sepal.width': '3.3', 'petal.length': '5.7', 'petal.width': '2.5', 'variety': 'Virginica'}
{'sepal.length': '6.7', 'sepal.width': '3', 'petal.length': '5.2', 'petal.width': '2.3', 'variety': 'Virginica'}
{'sepal.length': '6.3', 'sepal.width': '2.5', 'petal.length': '5', 'petal.width': '1.9', 'variety': 'Virginica'}
{'sepal.length': '6.5', 'sepal.width': '3', 'petal.length': '5.2', 'petal.width': '2', 'variety': 'Virginica'}
{'sepal.length': '6.2', 'sepal.width': '3.4', 'petal.length': '5.4', 'petal.width': '2.3', 'variety': 'Virginica'}
{'sepal.length': '5.9', 'sepal.width': '3', 'petal.length': '5.1', 'petal.width': '1.8', 'variety': 'Virginica'}

In [9]:
list=[]
list.append({'name':'Rahul','age':32})
list.append({'name':'Rahul12','age':35})
list.append({'name':'Rahul34','age':36})

In [10]:
from csv import DictWriter

In [11]:
with open("C://data//samplename1.csv","w",newline='') as op:
    writer=DictWriter(op,["name","age"])
    writer.writeheader()
    writer.writerows(list)

In [67]:
help(DictWriter)

Help on class DictWriter in module csv:

class DictWriter(builtins.object)
 |  DictWriter(f, fieldnames, restval='', extrasaction='raise', dialect='excel', *args, **kwds)
 |
 |  Methods defined here:
 |
 |  __init__(self, f, fieldnames, restval='', extrasaction='raise', dialect='excel', *args, **kwds)
 |      Initialize self.  See help(type(self)) for accurate signature.
 |
 |  writeheader(self)
 |
 |  writerow(self, rowdict)
 |
 |  writerows(self, rowdicts)
 |
 |  ----------------------------------------------------------------------
 |  Data descriptors defined here:
 |
 |  __dict__
 |      dictionary for instance variables (if defined)
 |
 |  __weakref__
 |      list of weak references to the object (if defined)

In [76]:
from csv import DictReader
class CsvHelper:
   
    
    def read(self,inputfilepath):
        with open(inputfilepath,"r") as ip:
            reader=DictReader(ip)
            for data in reader:
                print(data)
             
         
                
    def write(self,datalst,fieldnames,outputfilepath):
        with open(outputfilepath,"w",newline='') as op:
            writer=DictWriter(op,fieldnames)
            writer.writeheader()
            writer.writerows(datalst)

In [77]:
csvhelper=CsvHelper()

In [78]:
csvhelper.read('C://data/iris.csv')

{'sepal.length': '5.1', 'sepal.width': '3.5', 'petal.length': '1.4', 'petal.width': '.2', 'variety': 'Setosa'}
{'sepal.length': '4.9', 'sepal.width': '3', 'petal.length': '1.4', 'petal.width': '.2', 'variety': 'Setosa'}
{'sepal.length': '4.7', 'sepal.width': '3.2', 'petal.length': '1.3', 'petal.width': '.2', 'variety': 'Setosa'}
{'sepal.length': '4.6', 'sepal.width': '3.1', 'petal.length': '1.5', 'petal.width': '.2', 'variety': 'Setosa'}
{'sepal.length': '5', 'sepal.width': '3.6', 'petal.length': '1.4', 'petal.width': '.2', 'variety': 'Setosa'}
{'sepal.length': '5.4', 'sepal.width': '3.9', 'petal.length': '1.7', 'petal.width': '.4', 'variety': 'Setosa'}
{'sepal.length': '4.6', 'sepal.width': '3.4', 'petal.length': '1.4', 'petal.width': '.3', 'variety': 'Setosa'}
{'sepal.length': '5', 'sepal.width': '3.4', 'petal.length': '1.5', 'petal.width': '.2', 'variety': 'Setosa'}
{'sepal.length': '4.4', 'sepal.width': '2.9', 'petal.length': '1.4', 'petal.width': '.2', 'variety': 'Setosa'}
{'sepal.length': '4.9', 'sepal.width': '3.1', 'petal.length': '1.5', 'petal.width': '.1', 'variety': 'Setosa'}
{'sepal.length': '5.4', 'sepal.width': '3.7', 'petal.length': '1.5', 'petal.width': '.2', 'variety': 'Setosa'}
{'sepal.length': '4.8', 'sepal.width': '3.4', 'petal.length': '1.6', 'petal.width': '.2', 'variety': 'Setosa'}
{'sepal.length': '4.8', 'sepal.width': '3', 'petal.length': '1.4', 'petal.width': '.1', 'variety': 'Setosa'}
{'sepal.length': '4.3', 'sepal.width': '3', 'petal.length': '1.1', 'petal.width': '.1', 'variety': 'Setosa'}
{'sepal.length': '5.8', 'sepal.width': '4', 'petal.length': '1.2', 'petal.width': '.2', 'variety': 'Setosa'}
{'sepal.length': '5.7', 'sepal.width': '4.4', 'petal.length': '1.5', 'petal.width': '.4', 'variety': 'Setosa'}
{'sepal.length': '5.4', 'sepal.width': '3.9', 'petal.length': '1.3', 'petal.width': '.4', 'variety': 'Setosa'}
{'sepal.length': '5.1', 'sepal.width': '3.5', 'petal.length': '1.4', 'petal.width': '.3', 'variety': 'Setosa'}
{'sepal.length': '5.7', 'sepal.width': '3.8', 'petal.length': '1.7', 'petal.width': '.3', 'variety': 'Setosa'}
{'sepal.length': '5.1', 'sepal.width': '3.8', 'petal.length': '1.5', 'petal.width': '.3', 'variety': 'Setosa'}
{'sepal.length': '5.4', 'sepal.width': '3.4', 'petal.length': '1.7', 'petal.width': '.2', 'variety': 'Setosa'}
{'sepal.length': '5.1', 'sepal.width': '3.7', 'petal.length': '1.5', 'petal.width': '.4', 'variety': 'Setosa'}
{'sepal.length': '4.6', 'sepal.width': '3.6', 'petal.length': '1', 'petal.width': '.2', 'variety': 'Setosa'}
{'sepal.length': '5.1', 'sepal.width': '3.3', 'petal.length': '1.7', 'petal.width': '.5', 'variety': 'Setosa'}
{'sepal.length': '4.8', 'sepal.width': '3.4', 'petal.length': '1.9', 'petal.width': '.2', 'variety': 'Setosa'}
{'sepal.length': '5', 'sepal.width': '3', 'petal.length': '1.6', 'petal.width': '.2', 'variety': 'Setosa'}
{'sepal.length': '5', 'sepal.width': '3.4', 'petal.length': '1.6', 'petal.width': '.4', 'variety': 'Setosa'}
{'sepal.length': '5.2', 'sepal.width': '3.5', 'petal.length': '1.5', 'petal.width': '.2', 'variety': 'Setosa'}
{'sepal.length': '5.2', 'sepal.width': '3.4', 'petal.length': '1.4', 'petal.width': '.2', 'variety': 'Setosa'}
{'sepal.length': '4.7', 'sepal.width': '3.2', 'petal.length': '1.6', 'petal.width': '.2', 'variety': 'Setosa'}
{'sepal.length': '4.8', 'sepal.width': '3.1', 'petal.length': '1.6', 'petal.width': '.2', 'variety': 'Setosa'}
{'sepal.length': '5.4', 'sepal.width': '3.4', 'petal.length': '1.5', 'petal.width': '.4', 'variety': 'Setosa'}
{'sepal.length': '5.2', 'sepal.width': '4.1', 'petal.length': '1.5', 'petal.width': '.1', 'variety': 'Setosa'}
{'sepal.length': '5.5', 'sepal.width': '4.2', 'petal.length': '1.4', 'petal.width': '.2', 'variety': 'Setosa'}
{'sepal.length': '4.9', 'sepal.width': '3.1', 'petal.length': '1.5', 'petal.width': '.2', 'variety': 'Setosa'}
{'sepal.length': '5', 'sepal.width': '3.2', 'petal.length': '1.2', 'petal.width': '.2', 'variety': 'Setosa'}
{'sepal.length': '5.5', 'sepal.width': '3.5', 'petal.length': '1.3', 'petal.width': '.2', 'variety': 'Setosa'}
{'sepal.length': '4.9', 'sepal.width': '3.6', 'petal.length': '1.4', 'petal.width': '.1', 'variety': 'Setosa'}
{'sepal.length': '4.4', 'sepal.width': '3', 'petal.length': '1.3', 'petal.width': '.2', 'variety': 'Setosa'}
{'sepal.length': '5.1', 'sepal.width': '3.4', 'petal.length': '1.5', 'petal.width': '.2', 'variety': 'Setosa'}
{'sepal.length': '5', 'sepal.width': '3.5', 'petal.length': '1.3', 'petal.width': '.3', 'variety': 'Setosa'}
{'sepal.length': '4.5', 'sepal.width': '2.3', 'petal.length': '1.3', 'petal.width': '.3', 'variety': 'Setosa'}
{'sepal.length': '4.4', 'sepal.width': '3.2', 'petal.length': '1.3', 'petal.width': '.2', 'variety': 'Setosa'}
{'sepal.length': '5', 'sepal.width': '3.5', 'petal.length': '1.6', 'petal.width': '.6', 'variety': 'Setosa'}
{'sepal.length': '5.1', 'sepal.width': '3.8', 'petal.length': '1.9', 'petal.width': '.4', 'variety': 'Setosa'}
{'sepal.length': '4.8', 'sepal.width': '3', 'petal.length': '1.4', 'petal.width': '.3', 'variety': 'Setosa'}
{'sepal.length': '5.1', 'sepal.width': '3.8', 'petal.length': '1.6', 'petal.width': '.2', 'variety': 'Setosa'}
{'sepal.length': '4.6', 'sepal.width': '3.2', 'petal.length': '1.4', 'petal.width': '.2', 'variety': 'Setosa'}
{'sepal.length': '5.3', 'sepal.width': '3.7', 'petal.length': '1.5', 'petal.width': '.2', 'variety': 'Setosa'}
{'sepal.length': '5', 'sepal.width': '3.3', 'petal.length': '1.4', 'petal.width': '.2', 'variety': 'Setosa'}
{'sepal.length': '7', 'sepal.width': '3.2', 'petal.length': '4.7', 'petal.width': '1.4', 'variety': 'Versicolor'}
{'sepal.length': '6.4', 'sepal.width': '3.2', 'petal.length': '4.5', 'petal.width': '1.5', 'variety': 'Versicolor'}
{'sepal.length': '6.9', 'sepal.width': '3.1', 'petal.length': '4.9', 'petal.width': '1.5', 'variety': 'Versicolor'}
{'sepal.length': '5.5', 'sepal.width': '2.3', 'petal.length': '4', 'petal.width': '1.3', 'variety': 'Versicolor'}
{'sepal.length': '6.5', 'sepal.width': '2.8', 'petal.length': '4.6', 'petal.width': '1.5', 'variety': 'Versicolor'}
{'sepal.length': '5.7', 'sepal.width': '2.8', 'petal.length': '4.5', 'petal.width': '1.3', 'variety': 'Versicolor'}
{'sepal.length': '6.3', 'sepal.width': '3.3', 'petal.length': '4.7', 'petal.width': '1.6', 'variety': 'Versicolor'}
{'sepal.length': '4.9', 'sepal.width': '2.4', 'petal.length': '3.3', 'petal.width': '1', 'variety': 'Versicolor'}
{'sepal.length': '6.6', 'sepal.width': '2.9', 'petal.length': '4.6', 'petal.width': '1.3', 'variety': 'Versicolor'}
{'sepal.length': '5.2', 'sepal.width': '2.7', 'petal.length': '3.9', 'petal.width': '1.4', 'variety': 'Versicolor'}
{'sepal.length': '5', 'sepal.width': '2', 'petal.length': '3.5', 'petal.width': '1', 'variety': 'Versicolor'}
{'sepal.length': '5.9', 'sepal.width': '3', 'petal.length': '4.2', 'petal.width': '1.5', 'variety': 'Versicolor'}
{'sepal.length': '6', 'sepal.width': '2.2', 'petal.length': '4', 'petal.width': '1', 'variety': 'Versicolor'}
{'sepal.length': '6.1', 'sepal.width': '2.9', 'petal.length': '4.7', 'petal.width': '1.4', 'variety': 'Versicolor'}
{'sepal.length': '5.6', 'sepal.width': '2.9', 'petal.length': '3.6', 'petal.width': '1.3', 'variety': 'Versicolor'}
{'sepal.length': '6.7', 'sepal.width': '3.1', 'petal.length': '4.4', 'petal.width': '1.4', 'variety': 'Versicolor'}
{'sepal.length': '5.6', 'sepal.width': '3', 'petal.length': '4.5', 'petal.width': '1.5', 'variety': 'Versicolor'}
{'sepal.length': '5.8', 'sepal.width': '2.7', 'petal.length': '4.1', 'petal.width': '1', 'variety': 'Versicolor'}
{'sepal.length': '6.2', 'sepal.width': '2.2', 'petal.length': '4.5', 'petal.width': '1.5', 'variety': 'Versicolor'}
{'sepal.length': '5.6', 'sepal.width': '2.5', 'petal.length': '3.9', 'petal.width': '1.1', 'variety': 'Versicolor'}
{'sepal.length': '5.9', 'sepal.width': '3.2', 'petal.length': '4.8', 'petal.width': '1.8', 'variety': 'Versicolor'}
{'sepal.length': '6.1', 'sepal.width': '2.8', 'petal.length': '4', 'petal.width': '1.3', 'variety': 'Versicolor'}
{'sepal.length': '6.3', 'sepal.width': '2.5', 'petal.length': '4.9', 'petal.width': '1.5', 'variety': 'Versicolor'}
{'sepal.length': '6.1', 'sepal.width': '2.8', 'petal.length': '4.7', 'petal.width': '1.2', 'variety': 'Versicolor'}
{'sepal.length': '6.4', 'sepal.width': '2.9', 'petal.length': '4.3', 'petal.width': '1.3', 'variety': 'Versicolor'}
{'sepal.length': '6.6', 'sepal.width': '3', 'petal.length': '4.4', 'petal.width': '1.4', 'variety': 'Versicolor'}
{'sepal.length': '6.8', 'sepal.width': '2.8', 'petal.length': '4.8', 'petal.width': '1.4', 'variety': 'Versicolor'}
{'sepal.length': '6.7', 'sepal.width': '3', 'petal.length': '5', 'petal.width': '1.7', 'variety': 'Versicolor'}
{'sepal.length': '6', 'sepal.width': '2.9', 'petal.length': '4.5', 'petal.width': '1.5', 'variety': 'Versicolor'}
{'sepal.length': '5.7', 'sepal.width': '2.6', 'petal.length': '3.5', 'petal.width': '1', 'variety': 'Versicolor'}
{'sepal.length': '5.5', 'sepal.width': '2.4', 'petal.length': '3.8', 'petal.width': '1.1', 'variety': 'Versicolor'}
{'sepal.length': '5.5', 'sepal.width': '2.4', 'petal.length': '3.7', 'petal.width': '1', 'variety': 'Versicolor'}
{'sepal.length': '5.8', 'sepal.width': '2.7', 'petal.length': '3.9', 'petal.width': '1.2', 'variety': 'Versicolor'}
{'sepal.length': '6', 'sepal.width': '2.7', 'petal.length': '5.1', 'petal.width': '1.6', 'variety': 'Versicolor'}
{'sepal.length': '5.4', 'sepal.width': '3', 'petal.length': '4.5', 'petal.width': '1.5', 'variety': 'Versicolor'}
{'sepal.length': '6', 'sepal.width': '3.4', 'petal.length': '4.5', 'petal.width': '1.6', 'variety': 'Versicolor'}
{'sepal.length': '6.7', 'sepal.width': '3.1', 'petal.length': '4.7', 'petal.width': '1.5', 'variety': 'Versicolor'}
{'sepal.length': '6.3', 'sepal.width': '2.3', 'petal.length': '4.4', 'petal.width': '1.3', 'variety': 'Versicolor'}
{'sepal.length': '5.6', 'sepal.width': '3', 'petal.length': '4.1', 'petal.width': '1.3', 'variety': 'Versicolor'}
{'sepal.length': '5.5', 'sepal.width': '2.5', 'petal.length': '4', 'petal.width': '1.3', 'variety': 'Versicolor'}
{'sepal.length': '5.5', 'sepal.width': '2.6', 'petal.length': '4.4', 'petal.width': '1.2', 'variety': 'Versicolor'}
{'sepal.length': '6.1', 'sepal.width': '3', 'petal.length': '4.6', 'petal.width': '1.4', 'variety': 'Versicolor'}
{'sepal.length': '5.8', 'sepal.width': '2.6', 'petal.length': '4', 'petal.width': '1.2', 'variety': 'Versicolor'}
{'sepal.length': '5', 'sepal.width': '2.3', 'petal.length': '3.3', 'petal.width': '1', 'variety': 'Versicolor'}
{'sepal.length': '5.6', 'sepal.width': '2.7', 'petal.length': '4.2', 'petal.width': '1.3', 'variety': 'Versicolor'}
{'sepal.length': '5.7', 'sepal.width': '3', 'petal.length': '4.2', 'petal.width': '1.2', 'variety': 'Versicolor'}
{'sepal.length': '5.7', 'sepal.width': '2.9', 'petal.length': '4.2', 'petal.width': '1.3', 'variety': 'Versicolor'}
{'sepal.length': '6.2', 'sepal.width': '2.9', 'petal.length': '4.3', 'petal.width': '1.3', 'variety': 'Versicolor'}
{'sepal.length': '5.1', 'sepal.width': '2.5', 'petal.length': '3', 'petal.width': '1.1', 'variety': 'Versicolor'}
{'sepal.length': '5.7', 'sepal.width': '2.8', 'petal.length': '4.1', 'petal.width': '1.3', 'variety': 'Versicolor'}
{'sepal.length': '6.3', 'sepal.width': '3.3', 'petal.length': '6', 'petal.width': '2.5', 'variety': 'Virginica'}
{'sepal.length': '5.8', 'sepal.width': '2.7', 'petal.length': '5.1', 'petal.width': '1.9', 'variety': 'Virginica'}
{'sepal.length': '7.1', 'sepal.width': '3', 'petal.length': '5.9', 'petal.width': '2.1', 'variety': 'Virginica'}
{'sepal.length': '6.3', 'sepal.width': '2.9', 'petal.length': '5.6', 'petal.width': '1.8', 'variety': 'Virginica'}
{'sepal.length': '6.5', 'sepal.width': '3', 'petal.length': '5.8', 'petal.width': '2.2', 'variety': 'Virginica'}
{'sepal.length': '7.6', 'sepal.width': '3', 'petal.length': '6.6', 'petal.width': '2.1', 'variety': 'Virginica'}
{'sepal.length': '4.9', 'sepal.width': '2.5', 'petal.length': '4.5', 'petal.width': '1.7', 'variety': 'Virginica'}
{'sepal.length': '7.3', 'sepal.width': '2.9', 'petal.length': '6.3', 'petal.width': '1.8', 'variety': 'Virginica'}
{'sepal.length': '6.7', 'sepal.width': '2.5', 'petal.length': '5.8', 'petal.width': '1.8', 'variety': 'Virginica'}
{'sepal.length': '7.2', 'sepal.width': '3.6', 'petal.length': '6.1', 'petal.width': '2.5', 'variety': 'Virginica'}
{'sepal.length': '6.5', 'sepal.width': '3.2', 'petal.length': '5.1', 'petal.width': '2', 'variety': 'Virginica'}
{'sepal.length': '6.4', 'sepal.width': '2.7', 'petal.length': '5.3', 'petal.width': '1.9', 'variety': 'Virginica'}
{'sepal.length': '6.8', 'sepal.width': '3', 'petal.length': '5.5', 'petal.width': '2.1', 'variety': 'Virginica'}
{'sepal.length': '5.7', 'sepal.width': '2.5', 'petal.length': '5', 'petal.width': '2', 'variety': 'Virginica'}
{'sepal.length': '5.8', 'sepal.width': '2.8', 'petal.length': '5.1', 'petal.width': '2.4', 'variety': 'Virginica'}
{'sepal.length': '6.4', 'sepal.width': '3.2', 'petal.length': '5.3', 'petal.width': '2.3', 'variety': 'Virginica'}
{'sepal.length': '6.5', 'sepal.width': '3', 'petal.length': '5.5', 'petal.width': '1.8', 'variety': 'Virginica'}
{'sepal.length': '7.7', 'sepal.width': '3.8', 'petal.length': '6.7', 'petal.width': '2.2', 'variety': 'Virginica'}
{'sepal.length': '7.7', 'sepal.width': '2.6', 'petal.length': '6.9', 'petal.width': '2.3', 'variety': 'Virginica'}
{'sepal.length': '6', 'sepal.width': '2.2', 'petal.length': '5', 'petal.width': '1.5', 'variety': 'Virginica'}
{'sepal.length': '6.9', 'sepal.width': '3.2', 'petal.length': '5.7', 'petal.width': '2.3', 'variety': 'Virginica'}
{'sepal.length': '5.6', 'sepal.width': '2.8', 'petal.length': '4.9', 'petal.width': '2', 'variety': 'Virginica'}
{'sepal.length': '7.7', 'sepal.width': '2.8', 'petal.length': '6.7', 'petal.width': '2', 'variety': 'Virginica'}
{'sepal.length': '6.3', 'sepal.width': '2.7', 'petal.length': '4.9', 'petal.width': '1.8', 'variety': 'Virginica'}
{'sepal.length': '6.7', 'sepal.width': '3.3', 'petal.length': '5.7', 'petal.width': '2.1', 'variety': 'Virginica'}
{'sepal.length': '7.2', 'sepal.width': '3.2', 'petal.length': '6', 'petal.width': '1.8', 'variety': 'Virginica'}
{'sepal.length': '6.2', 'sepal.width': '2.8', 'petal.length': '4.8', 'petal.width': '1.8', 'variety': 'Virginica'}
{'sepal.length': '6.1', 'sepal.width': '3', 'petal.length': '4.9', 'petal.width': '1.8', 'variety': 'Virginica'}
{'sepal.length': '6.4', 'sepal.width': '2.8', 'petal.length': '5.6', 'petal.width': '2.1', 'variety': 'Virginica'}
{'sepal.length': '7.2', 'sepal.width': '3', 'petal.length': '5.8', 'petal.width': '1.6', 'variety': 'Virginica'}
{'sepal.length': '7.4', 'sepal.width': '2.8', 'petal.length': '6.1', 'petal.width': '1.9', 'variety': 'Virginica'}
{'sepal.length': '7.9', 'sepal.width': '3.8', 'petal.length': '6.4', 'petal.width': '2', 'variety': 'Virginica'}
{'sepal.length': '6.4', 'sepal.width': '2.8', 'petal.length': '5.6', 'petal.width': '2.2', 'variety': 'Virginica'}
{'sepal.length': '6.3', 'sepal.width': '2.8', 'petal.length': '5.1', 'petal.width': '1.5', 'variety': 'Virginica'}
{'sepal.length': '6.1', 'sepal.width': '2.6', 'petal.length': '5.6', 'petal.width': '1.4', 'variety': 'Virginica'}
{'sepal.length': '7.7', 'sepal.width': '3', 'petal.length': '6.1', 'petal.width': '2.3', 'variety': 'Virginica'}
{'sepal.length': '6.3', 'sepal.width': '3.4', 'petal.length': '5.6', 'petal.width': '2.4', 'variety': 'Virginica'}
{'sepal.length': '6.4', 'sepal.width': '3.1', 'petal.length': '5.5', 'petal.width': '1.8', 'variety': 'Virginica'}
{'sepal.length': '6', 'sepal.width': '3', 'petal.length': '4.8', 'petal.width': '1.8', 'variety': 'Virginica'}
{'sepal.length': '6.9', 'sepal.width': '3.1', 'petal.length': '5.4', 'petal.width': '2.1', 'variety': 'Virginica'}
{'sepal.length': '6.7', 'sepal.width': '3.1', 'petal.length': '5.6', 'petal.width': '2.4', 'variety': 'Virginica'}
{'sepal.length': '6.9', 'sepal.width': '3.1', 'petal.length': '5.1', 'petal.width': '2.3', 'variety': 'Virginica'}
{'sepal.length': '5.8', 'sepal.width': '2.7', 'petal.length': '5.1', 'petal.width': '1.9', 'variety': 'Virginica'}
{'sepal.length': '6.8', 'sepal.width': '3.2', 'petal.length': '5.9', 'petal.width': '2.3', 'variety': 'Virginica'}
{'sepal.length': '6.7', 'sepal.width': '3.3', 'petal.length': '5.7', 'petal.width': '2.5', 'variety': 'Virginica'}
{'sepal.length': '6.7', 'sepal.width': '3', 'petal.length': '5.2', 'petal.width': '2.3', 'variety': 'Virginica'}
{'sepal.length': '6.3', 'sepal.width': '2.5', 'petal.length': '5', 'petal.width': '1.9', 'variety': 'Virginica'}
{'sepal.length': '6.5', 'sepal.width': '3', 'petal.length': '5.2', 'petal.width': '2', 'variety': 'Virginica'}
{'sepal.length': '6.2', 'sepal.width': '3.4', 'petal.length': '5.4', 'petal.width': '2.3', 'variety': 'Virginica'}
{'sepal.length': '5.9', 'sepal.width': '3', 'petal.length': '5.1', 'petal.width': '1.8', 'variety': 'Virginica'}

In [79]:
import pandas as pd

In [80]:
data=pd.read_csv("C://data//iris.csv")

In [82]:
data.shape

(150, 5)

In [83]:
data.columns

Index(['sepal.length', 'sepal.width', 'petal.length', 'petal.width',
       'variety'],
      dtype='object')

In [84]:
data['variety'].unique()

array(['Setosa', 'Versicolor', 'Virginica'], dtype=object)

In [85]:
data['variety'].value_counts()

Setosa        50
Versicolor    50
Virginica     50
Name: variety, dtype: int64

In [88]:
iris=pd.read_excel("C://data/iris.xls")

In [89]:
iris.head()

   sepal.length  sepal.width  petal.length  petal.width variety
0           5.1          3.5           1.4          0.2  Setosa
1           4.9          3.0           1.4          0.2  Setosa
2           4.7          3.2           1.3          0.2  Setosa
3           4.6          3.1           1.5          0.2  Setosa
4           5.0          3.6           1.4          0.2  Setosa

In [90]:
todos=pd.read_json("https://jsonplaceholder.typicode.com/todos")

In [92]:
todos.to_html("C://data//iris.html")

In [93]:
todos.columns

Index(['userId', 'id', 'title', 'completed'], dtype='object')

In [94]:
todos[['userId','id']]

     userId   id
0         1    1
1         1    2
2         1    3
3         1    4
4         1    5
..      ...  ...
195      10  196
196      10  197
197      10  198
198      10  199
199      10  200

[200 rows x 2 columns]

In [95]:
todos.head()

   userId  id                                              title  completed
0       1   1                                 delectus aut autem      False
1       1   2                 quis ut nam facilis et officia qui      False
2       1   3                                fugiat veniam minus      False
3       1   4                                   et porro tempora       True
4       1   5  laboriosam mollitia et enim quasi adipisci qui...      False

In [96]:
todos.T

,0,1,2,3,4,5,6,7,8,9,...,190,191,192,193,194,195,196,197,198,199
userId,1,1,1,1,1,1,1,1,1,1,...,10,10,10,10,10,10,10,10,10,10
id,1,2,3,4,5,6,7,8,9,10,...,191,192,193,194,195,196,197,198,199,200
title,delectus aut autem,quis ut nam facilis et officia qui,fugiat veniam minus,et porro tempora,laboriosam mollitia et enim quasi adipisci qui...,qui ullam ratione quibusdam voluptatem quia omnis,illo expedita consequatur quia in,quo adipisci enim quam ut ab,molestiae perspiciatis ipsa,illo est ratione doloremque quia maiores aut,...,temporibus atque distinctio omnis eius impedit...,ut quas possimus exercitationem sint voluptates,rerum debitis voluptatem qui eveniet tempora d...,sed ut vero sit molestiae,rerum ex veniam mollitia voluptatibus pariatur,consequuntur aut ut fugit similique,dignissimos quo nobis earum saepe,quis eius est sint explicabo,numquam repellendus a magnam,ipsam aperiam voluptates qui
completed,False,False,False,True,False,False,False,True,False,True,...,True,False,True,False,True,True,True,True,True,False

In [98]:
todos['id'].max()

200

In [99]:
todos['id'].min()

1

In [100]:
todos['id'].sum()

20100

In [101]:
todos['id'].mean()

100.5

In [102]:
todos['id'].std()

57.879184513951124

In [103]:
todos['id'].describe()

count    200.000000
mean     100.500000
std       57.879185
min        1.000000
25%       50.750000
50%      100.500000
75%      150.250000
max      200.000000
Name: id, dtype: float64

In [104]:
for data in todos.iterrows():
    print(data)

(0, userId                        1
id                            1
title        delectus aut autem
completed                 False
Name: 0, dtype: object)
(1, userId                                        1
id                                            2
title        quis ut nam facilis et officia qui
completed                                 False
Name: 1, dtype: object)
(2, userId                         1
id                             3
title        fugiat veniam minus
completed                  False
Name: 2, dtype: object)
(3, userId                      1
id                          4
title        et porro tempora
completed                True
Name: 3, dtype: object)
(4, userId                                                       1
id                                                           5
title        laboriosam mollitia et enim quasi adipisci qui...
completed                                                False
Name: 4, dtype: object)
(5, userId                                                       1
id                                                           6
title        qui ullam ratione quibusdam voluptatem quia omnis
completed                                                False
Name: 5, dtype: object)
(6, userId                                       1
id                                           7
title        illo expedita consequatur quia in
completed                                False
Name: 6, dtype: object)
(7, userId                                  1
id                                      8
title        quo adipisci enim quam ut ab
completed                            True
Name: 7, dtype: object)
(8, userId                                 1
id                                     9
title        molestiae perspiciatis ipsa
completed                          False
Name: 8, dtype: object)
(9, userId                                                  1
id                                                     10
title        illo est ratione doloremque quia maiores aut
completed                                            True
Name: 9, dtype: object)
(10, userId                                 1
id                                    11
title        vero rerum temporibus dolor
completed                           True
Name: 10, dtype: object)
(11, userId                                 1
id                                    12
title        ipsa repellendus fugit nisi
completed                           True
Name: 11, dtype: object)
(12, userId                         1
id                            13
title        et doloremque nulla
completed                  False
Name: 12, dtype: object)
(13, userId                                                    1
id                                                       14
title        repellendus sunt dolores architecto voluptatum
completed                                              True
Name: 13, dtype: object)
(14, userId                                 1
id                                    15
title        ab voluptatum amet voluptas
completed                           True
Name: 14, dtype: object)
(15, userId                                                  1
id                                                     16
title        accusamus eos facilis sint et aut voluptatem
completed                                            True
Name: 15, dtype: object)
(16, userId                                     1
id                                        17
title        quo laboriosam deleniti aut qui
completed                               True
Name: 16, dtype: object)
(17, userId                                                  1
id                                                     18
title        dolorum est consequatur ea mollitia in culpa
completed                                           False
Name: 17, dtype: object)
(18, userId                                                       1
id                                                          19
title        molestiae ipsa aut voluptatibus pariatur dolor...
completed                                                 True
Name: 18, dtype: object)
(19, userId                                               1
id                                                  20
title        ullam nobis libero sapiente ad optio sint
completed                                         True
Name: 19, dtype: object)
(20, userId                                                       2
id                                                          21
title        suscipit repellat esse quibusdam voluptatem in...
completed                                                False
Name: 20, dtype: object)
(21, userId                                                   2
id                                                      22
title        distinctio vitae autem nihil ut molestias quo
completed                                             True
Name: 21, dtype: object)
(22, userId                                                       2
id                                                          23
title        et itaque necessitatibus maxime molestiae qui ...
completed                                                False
Name: 22, dtype: object)
(23, userId                                                       2
id                                                          24
title        adipisci non ad dicta qui amet quaerat dolorib...
completed                                                False
Name: 23, dtype: object)
(24, userId                                                       2
id                                                          25
title        voluptas quo tenetur perspiciatis explicabo natus
completed                                                 True
Name: 24, dtype: object)
(25, userId                       2
id                          26
title        aliquam aut quasi
completed                 True
Name: 25, dtype: object)
(26, userId                                 2
id                                    27
title        veritatis pariatur delectus
completed                           True
Name: 26, dtype: object)
(27, userId                                       2
id                                          28
title        nesciunt totam sit blanditiis sit
completed                                False
Name: 27, dtype: object)
(28, userId                         2
id                            29
title        laborum aut in quam
completed                  False
Name: 28, dtype: object)
(29, userId                                                       2
id                                                          30
title        nemo perspiciatis repellat ut dolor libero com...
completed                                                 True
Name: 29, dtype: object)
(30, userId                                               2
id                                                  31
title        repudiandae totam in est sint facere fuga
completed                                        False
Name: 30, dtype: object)
(31, userId                                        2
id                                           32
title        earum doloribus ea doloremque quis
completed                                 False
Name: 31, dtype: object)
(32, userId                       2
id                          33
title        sint sit aut vero
completed                False
Name: 32, dtype: object)
(33, userId                                               2
id                                                  34
title        porro aut necessitatibus eaque distinctio
completed                                        False
Name: 33, dtype: object)
(34, userId                                                    2
id                                                       35
title        repellendus veritatis molestias dicta incidunt
completed                                              True
Name: 34, dtype: object)
(35, userId                                                       2
id                                                          36
title        excepturi deleniti adipisci voluptatem et nequ...
completed                                                 True
Name: 35, dtype: object)
(36, userId                      2
id                         37
title        sunt cum tempora
completed               False
Name: 36, dtype: object)
(37, userId                    2
id                       38
title        totam quia non
completed             False
Name: 37, dtype: object)
(38, userId                                                       2
id                                                          39
title        doloremque quibusdam asperiores libero corrupt...
completed                                                False
Name: 38, dtype: object)
(39, userId                              2
id                                 40
title        totam atque quo nesciunt
completed                        True
Name: 39, dtype: object)
(40, userId                                                       3
id                                                          41
title        aliquid amet impedit consequatur aspernatur pl...
completed                                                False
Name: 40, dtype: object)
(41, userId                                             3
id                                                42
title        rerum perferendis error quia ut eveniet
completed                                      False
Name: 41, dtype: object)
(42, userId                                     3
id                                        43
title        tempore ut sint quis recusandae
completed                               True
Name: 42, dtype: object)
(43, userId                                                       3
id                                                          44
title        cum debitis quis accusamus doloremque ipsa nat...
completed                                                 True
Name: 43, dtype: object)
(44, userId                                                      3
id                                                         45
title        velit soluta adipisci molestias reiciendis harum
completed                                               False
Name: 44, dtype: object)
(45, userId                                                    3
id                                                       46
title        vel voluptatem repellat nihil placeat corporis
completed                                             False
Name: 45, dtype: object)
(46, userId                                    3
id                                       47
title        nam qui rerum fugiat accusamus
completed                             False
Name: 46, dtype: object)
(47, userId                                  3
id                                     48
title        sit reprehenderit omnis quia
completed                           False
Name: 47, dtype: object)
(48, userId                                                       3
id                                                          49
title        ut necessitatibus aut maiores debitis officia ...
completed                                                False
Name: 48, dtype: object)
(49, userId                                                       3
id                                                          50
title        cupiditate necessitatibus ullam aut quis dolor...
completed                                                 True
Name: 49, dtype: object)
(50, userId                                            3
id                                               51
title        distinctio exercitationem ab doloribus
completed                                     False
Name: 50, dtype: object)
(51, userId                                                       3
id                                                          52
title        nesciunt dolorum quis recusandae ad pariatur r...
completed                                                False
Name: 51, dtype: object)
(52, userId                                                      3
id                                                         53
title        qui labore est occaecati recusandae aliquid quam
completed                                               False
Name: 52, dtype: object)
(53, userId                                         3
id                                            54
title        quis et est ut voluptate quam dolor
completed                                   True
Name: 53, dtype: object)
(54, userId                                                       3
id                                                          55
title        voluptatum omnis minima qui occaecati providen...
completed                                                 True
Name: 54, dtype: object)
(55, userId                                 3
id                                    56
title        deleniti ea temporibus enim
completed                           True
Name: 55, dtype: object)
(56, userId                                                       3
id                                                          57
title        pariatur et magnam ea doloribus similique volu...
completed                                                False
Name: 56, dtype: object)
(57, userId                                                       3
id                                                          58
title        est dicta totam qui explicabo doloribus qui di...
completed                                                False
Name: 57, dtype: object)
(58, userId                                                       3
id                                                          59
title        perspiciatis velit id laborum placeat iusto et...
completed                                                False
Name: 58, dtype: object)
(59, userId                                         3
id                                            60
title        et sequi qui architecto ut adipisci
completed                                   True
Name: 59, dtype: object)
(60, userId                               4
id                                  61
title        odit optio omnis qui sunt
completed                         True
Name: 60, dtype: object)
(61, userId                                                   4
id                                                      62
title        et placeat et tempore aspernatur sint numquam
completed                                            False
Name: 61, dtype: object)
(62, userId                                                  4
id                                                     63
title        doloremque aut dolores quidem fuga qui nulla
completed                                            True
Name: 62, dtype: object)
(63, userId                                                       4
id                                                          64
title        voluptas consequatur qui ut quia magnam nemo esse
completed                                                False
Name: 63, dtype: object)
(64, userId                                                       4
id                                                          65
title        fugiat pariatur ratione ut asperiores necessit...
completed                                                False
Name: 64, dtype: object)
(65, userId                                                    4
id                                                       66
title        rerum eum molestias autem voluptatum sit optio
completed                                             False
Name: 65, dtype: object)
(66, userId                                                       4
id                                                          67
title        quia voluptatibus voluptatem quos similique ma...
completed                                                False
Name: 66, dtype: object)
(67, userId                                          4
id                                             68
title        aut id perspiciatis voluptatem iusto
completed                                   False
Name: 67, dtype: object)
(68, userId                                                       4
id                                                          69
title        doloribus sint dolorum ab adipisci itaque dign...
completed                                                False
Name: 68, dtype: object)
(69, userId                                                    4
id                                                       70
title        ut sequi accusantium et mollitia delectus sunt
completed                                             False
Name: 69, dtype: object)
(70, userId                           4
id                              71
title        aut velit saepe ullam
completed                    False
Name: 70, dtype: object)
(71, userId                                                       4
id                                                          72
title        praesentium facilis facere quis harum voluptat...
completed                                                False
Name: 71, dtype: object)
(72, userId                                                       4
id                                                          73
title        sint amet quia totam corporis qui exercitation...
completed                                                 True
Name: 72, dtype: object)
(73, userId                                                    4
id                                                       74
title        expedita tempore nobis eveniet laborum maiores
completed                                             False
Name: 73, dtype: object)
(74, userId                                           4
id                                              75
title        occaecati adipisci est possimus totam
completed                                    False
Name: 74, dtype: object)
(75, userId                       4
id                          76
title        sequi dolorem sed
completed                 True
Name: 75, dtype: object)
(76, userId                                                       4
id                                                          77
title        maiores aut nesciunt delectus exercitationem v...
completed                                                False
Name: 76, dtype: object)
(77, userId                                                       4
id                                                          78
title        reiciendis est magnam amet nemo iste recusanda...
completed                                                False
Name: 77, dtype: object)
(78, userId                        4
id                           79
title        eum ipsa maxime ut
completed                  True
Name: 78, dtype: object)
(79, userId                                                       4
id                                                          80
title        tempore molestias dolores rerum sequi voluptat...
completed                                                 True
Name: 79, dtype: object)
(80, userId                        5
id                           81
title        suscipit qui totam
completed                  True
Name: 80, dtype: object)
(81, userId                                      5
id                                         82
title        voluptates eum voluptas et dicta
completed                               False
Name: 81, dtype: object)
(82, userId                                          5
id                                             83
title        quidem at rerum quis ex aut sit quam
completed                                    True
Name: 82, dtype: object)
(83, userId                                 5
id                                    84
title        sunt veritatis ut voluptate
completed                          False
Name: 83, dtype: object)
(84, userId                       5
id                          85
title        et quia ad iste a

In [105]:
todos.shape

(200, 4)

In [106]:
todos.iloc[10:20,]

    userId  id                                              title  completed
10       1  11                        vero rerum temporibus dolor       True
11       1  12                        ipsa repellendus fugit nisi       True
12       1  13                                et doloremque nulla      False
13       1  14     repellendus sunt dolores architecto voluptatum       True
14       1  15                        ab voluptatum amet voluptas       True
15       1  16       accusamus eos facilis sint et aut voluptatem       True
16       1  17                    quo laboriosam deleniti aut qui       True
17       1  18       dolorum est consequatur ea mollitia in culpa      False
18       1  19  molestiae ipsa aut voluptatibus pariatur dolor...       True
19       1  20          ullam nobis libero sapiente ad optio sint       True

In [107]:
todos.iloc[10:20,1:3]

    id                                              title
10  11                        vero rerum temporibus dolor
11  12                        ipsa repellendus fugit nisi
12  13                                et doloremque nulla
13  14     repellendus sunt dolores architecto voluptatum
14  15                        ab voluptatum amet voluptas
15  16       accusamus eos facilis sint et aut voluptatem
16  17                    quo laboriosam deleniti aut qui
17  18       dolorum est consequatur ea mollitia in culpa
18  19  molestiae ipsa aut voluptatibus pariatur dolor...
19  20          ullam nobis libero sapiente ad optio sint

In [109]:
todos.loc[:,'id':'completed']

      id                                              title  completed
0      1                                 delectus aut autem      False
1      2                 quis ut nam facilis et officia qui      False
2      3                                fugiat veniam minus      False
3      4                                   et porro tempora       True
4      5  laboriosam mollitia et enim quasi adipisci qui...      False
..   ...                                                ...        ...
195  196                consequuntur aut ut fugit similique       True
196  197                  dignissimos quo nobis earum saepe       True
197  198                       quis eius est sint explicabo       True
198  199                       numquam repellendus a magnam       True
199  200                       ipsam aperiam voluptates qui      False

[200 rows x 3 columns]