In [3]:
def outer():
    print("Within Outside function")
    def inner():
        print("Within Inside function")
    print("Calling the inner function")
    inner()
    print("Calling done of the inner function")

In [4]:
outer()

Within Outside function
Calling the inner function
Within Inside function
Calling done of the inner function

In [5]:
def outer():
    print("Within Outside function")
    def inner():
        print("Within inner function")
        
    return inner

In [6]:
innerRef = outer() # holds inner function

Within Outside function

In [7]:
innerRef()

Within inner function

In [8]:
def outer(n1):
    def inner(n2):
        return n1*n2
        
    return inner

In [9]:
innerRef = outer(10)

In [11]:
print(innerRef(3))

30

In [ ]:
#Function can take another function as an argument

In [12]:
def hello():
    print("hello")
    
def bye():
    print("bye")

In [13]:
def sample(funRef):
    print("Going to call passed function")
    funRef()

In [14]:
sample(hello)

Going to call passed function
hello

In [15]:
sample(bye)

Going to call passed function
bye

In [16]:
def add(a,b):
    return a+b

In [17]:
def sub(a,b):
    return a-b

In [18]:
def sample(funRef,n1,n2):
    print("Going to call passed function")
    print(funRef(n1,n2))

In [19]:
sample(add,10,20)

Going to call passed function
30

In [20]:
def power(n1,n2):
    return n1 ** n2

In [21]:
def decorator_function(funRef):
    def wrapper(a,b):
        #a and b are string
        a1 = int(a)
        a2 = int(b)
        res=funRef(a1,a2)
        print("Result is",res)
    return wrapper

In [22]:
f1 = decorator_function(power)

In [23]:
f1("3","4")

Result is 81

In [24]:
with open("C://data//sample.txt","r") as op:
    data = op.read()
    print(data)

20
1
22
33
44
55
77
89
90

In [25]:
def readFileGenerator(filepath):
    with open(filepath,'r') as op:
        for line in op:
            yield line

In [26]:
reader = readFileGenerator("C://data//sample.txt")

In [27]:
print(next(reader))

20

In [28]:
print(next(reader))

1

In [29]:
for l in reader:
    print(l)

22

33

44

55

77

89

90

In [30]:
reader = readFileGenerator("C://data//sample.txt")

In [31]:
sum = 0
count = 0
for data in reader:
    sum = sum + int(data)
    count = count +1
avg = sum/count
print(avg)

47.888888888888886

In [32]:
import csv

In [33]:
with open("C://data//iris.csv","r") as ip:
    reader=csv.DictReader(ip)
    for data in reader:
        print(data)

{'sepal.length': '5.1', 'sepal.width': '3.5', 'petal.length': '1.4', 'petal.width': '.2', 'variety': 'Setosa'}
{'sepal.length': '4.9', 'sepal.width': '3', 'petal.length': '1.4', 'petal.width': '.2', 'variety': 'Setosa'}
{'sepal.length': '4.7', 'sepal.width': '3.2', 'petal.length': '1.3', 'petal.width': '.2', 'variety': 'Setosa'}
{'sepal.length': '4.6', 'sepal.width': '3.1', 'petal.length': '1.5', 'petal.width': '.2', 'variety': 'Setosa'}
{'sepal.length': '5', 'sepal.width': '3.6', 'petal.length': '1.4', 'petal.width': '.2', 'variety': 'Setosa'}
{'sepal.length': '5.4', 'sepal.width': '3.9', 'petal.length': '1.7', 'petal.width': '.4', 'variety': 'Setosa'}
{'sepal.length': '4.6', 'sepal.width': '3.4', 'petal.length': '1.4', 'petal.width': '.3', 'variety': 'Setosa'}
{'sepal.length': '5', 'sepal.width': '3.4', 'petal.length': '1.5', 'petal.width': '.2', 'variety': 'Setosa'}
{'sepal.length': '4.4', 'sepal.width': '2.9', 'petal.length': '1.4', 'petal.width': '.2', 'variety': 'Setosa'}
{'sepal.length': '4.9', 'sepal.width': '3.1', 'petal.length': '1.5', 'petal.width': '.1', 'variety': 'Setosa'}
{'sepal.length': '5.4', 'sepal.width': '3.7', 'petal.length': '1.5', 'petal.width': '.2', 'variety': 'Setosa'}
{'sepal.length': '4.8', 'sepal.width': '3.4', 'petal.length': '1.6', 'petal.width': '.2', 'variety': 'Setosa'}
{'sepal.length': '4.8', 'sepal.width': '3', 'petal.length': '1.4', 'petal.width': '.1', 'variety': 'Setosa'}
{'sepal.length': '4.3', 'sepal.width': '3', 'petal.length': '1.1', 'petal.width': '.1', 'variety': 'Setosa'}
{'sepal.length': '5.8', 'sepal.width': '4', 'petal.length': '1.2', 'petal.width': '.2', 'variety': 'Setosa'}
{'sepal.length': '5.7', 'sepal.width': '4.4', 'petal.length': '1.5', 'petal.width': '.4', 'variety': 'Setosa'}
{'sepal.length': '5.4', 'sepal.width': '3.9', 'petal.length': '1.3', 'petal.width': '.4', 'variety': 'Setosa'}
{'sepal.length': '5.1', 'sepal.width': '3.5', 'petal.length': '1.4', 'petal.width': '.3', 'variety': 'Setosa'}
{'sepal.length': '5.7', 'sepal.width': '3.8', 'petal.length': '1.7', 'petal.width': '.3', 'variety': 'Setosa'}
{'sepal.length': '5.1', 'sepal.width': '3.8', 'petal.length': '1.5', 'petal.width': '.3', 'variety': 'Setosa'}
{'sepal.length': '5.4', 'sepal.width': '3.4', 'petal.length': '1.7', 'petal.width': '.2', 'variety': 'Setosa'}
{'sepal.length': '5.1', 'sepal.width': '3.7', 'petal.length': '1.5', 'petal.width': '.4', 'variety': 'Setosa'}
{'sepal.length': '4.6', 'sepal.width': '3.6', 'petal.length': '1', 'petal.width': '.2', 'variety': 'Setosa'}
{'sepal.length': '5.1', 'sepal.width': '3.3', 'petal.length': '1.7', 'petal.width': '.5', 'variety': 'Setosa'}
{'sepal.length': '4.8', 'sepal.width': '3.4', 'petal.length': '1.9', 'petal.width': '.2', 'variety': 'Setosa'}
{'sepal.length': '5', 'sepal.width': '3', 'petal.length': '1.6', 'petal.width': '.2', 'variety': 'Setosa'}
{'sepal.length': '5', 'sepal.width': '3.4', 'petal.length': '1.6', 'petal.width': '.4', 'variety': 'Setosa'}
{'sepal.length': '5.2', 'sepal.width': '3.5', 'petal.length': '1.5', 'petal.width': '.2', 'variety': 'Setosa'}
{'sepal.length': '5.2', 'sepal.width': '3.4', 'petal.length': '1.4', 'petal.width': '.2', 'variety': 'Setosa'}
{'sepal.length': '4.7', 'sepal.width': '3.2', 'petal.length': '1.6', 'petal.width': '.2', 'variety': 'Setosa'}
{'sepal.length': '4.8', 'sepal.width': '3.1', 'petal.length': '1.6', 'petal.width': '.2', 'variety': 'Setosa'}
{'sepal.length': '5.4', 'sepal.width': '3.4', 'petal.length': '1.5', 'petal.width': '.4', 'variety': 'Setosa'}
{'sepal.length': '5.2', 'sepal.width': '4.1', 'petal.length': '1.5', 'petal.width': '.1', 'variety': 'Setosa'}
{'sepal.length': '5.5', 'sepal.width': '4.2', 'petal.length': '1.4', 'petal.width': '.2', 'variety': 'Setosa'}
{'sepal.length': '4.9', 'sepal.width': '3.1', 'petal.length': '1.5', 'petal.width': '.2', 'variety': 'Setosa'}
{'sepal.length': '5', 'sepal.width': '3.2', 'petal.length': '1.2', 'petal.width': '.2', 'variety': 'Setosa'}
{'sepal.length': '5.5', 'sepal.width': '3.5', 'petal.length': '1.3', 'petal.width': '.2', 'variety': 'Setosa'}
{'sepal.length': '4.9', 'sepal.width': '3.6', 'petal.length': '1.4', 'petal.width': '.1', 'variety': 'Setosa'}
{'sepal.length': '4.4', 'sepal.width': '3', 'petal.length': '1.3', 'petal.width': '.2', 'variety': 'Setosa'}
{'sepal.length': '5.1', 'sepal.width': '3.4', 'petal.length': '1.5', 'petal.width': '.2', 'variety': 'Setosa'}
{'sepal.length': '5', 'sepal.width': '3.5', 'petal.length': '1.3', 'petal.width': '.3', 'variety': 'Setosa'}
{'sepal.length': '4.5', 'sepal.width': '2.3', 'petal.length': '1.3', 'petal.width': '.3', 'variety': 'Setosa'}
{'sepal.length': '4.4', 'sepal.width': '3.2', 'petal.length': '1.3', 'petal.width': '.2', 'variety': 'Setosa'}
{'sepal.length': '5', 'sepal.width': '3.5', 'petal.length': '1.6', 'petal.width': '.6', 'variety': 'Setosa'}
{'sepal.length': '5.1', 'sepal.width': '3.8', 'petal.length': '1.9', 'petal.width': '.4', 'variety': 'Setosa'}
{'sepal.length': '4.8', 'sepal.width': '3', 'petal.length': '1.4', 'petal.width': '.3', 'variety': 'Setosa'}
{'sepal.length': '5.1', 'sepal.width': '3.8', 'petal.length': '1.6', 'petal.width': '.2', 'variety': 'Setosa'}
{'sepal.length': '4.6', 'sepal.width': '3.2', 'petal.length': '1.4', 'petal.width': '.2', 'variety': 'Setosa'}
{'sepal.length': '5.3', 'sepal.width': '3.7', 'petal.length': '1.5', 'petal.width': '.2', 'variety': 'Setosa'}
{'sepal.length': '5', 'sepal.width': '3.3', 'petal.length': '1.4', 'petal.width': '.2', 'variety': 'Setosa'}
{'sepal.length': '7', 'sepal.width': '3.2', 'petal.length': '4.7', 'petal.width': '1.4', 'variety': 'Versicolor'}
{'sepal.length': '6.4', 'sepal.width': '3.2', 'petal.length': '4.5', 'petal.width': '1.5', 'variety': 'Versicolor'}
{'sepal.length': '6.9', 'sepal.width': '3.1', 'petal.length': '4.9', 'petal.width': '1.5', 'variety': 'Versicolor'}
{'sepal.length': '5.5', 'sepal.width': '2.3', 'petal.length': '4', 'petal.width': '1.3', 'variety': 'Versicolor'}
{'sepal.length': '6.5', 'sepal.width': '2.8', 'petal.length': '4.6', 'petal.width': '1.5', 'variety': 'Versicolor'}
{'sepal.length': '5.7', 'sepal.width': '2.8', 'petal.length': '4.5', 'petal.width': '1.3', 'variety': 'Versicolor'}
{'sepal.length': '6.3', 'sepal.width': '3.3', 'petal.length': '4.7', 'petal.width': '1.6', 'variety': 'Versicolor'}
{'sepal.length': '4.9', 'sepal.width': '2.4', 'petal.length': '3.3', 'petal.width': '1', 'variety': 'Versicolor'}
{'sepal.length': '6.6', 'sepal.width': '2.9', 'petal.length': '4.6', 'petal.width': '1.3', 'variety': 'Versicolor'}
{'sepal.length': '5.2', 'sepal.width': '2.7', 'petal.length': '3.9', 'petal.width': '1.4', 'variety': 'Versicolor'}
{'sepal.length': '5', 'sepal.width': '2', 'petal.length': '3.5', 'petal.width': '1', 'variety': 'Versicolor'}
{'sepal.length': '5.9', 'sepal.width': '3', 'petal.length': '4.2', 'petal.width': '1.5', 'variety': 'Versicolor'}
{'sepal.length': '6', 'sepal.width': '2.2', 'petal.length': '4', 'petal.width': '1', 'variety': 'Versicolor'}
{'sepal.length': '6.1', 'sepal.width': '2.9', 'petal.length': '4.7', 'petal.width': '1.4', 'variety': 'Versicolor'}
{'sepal.length': '5.6', 'sepal.width': '2.9', 'petal.length': '3.6', 'petal.width': '1.3', 'variety': 'Versicolor'}
{'sepal.length': '6.7', 'sepal.width': '3.1', 'petal.length': '4.4', 'petal.width': '1.4', 'variety': 'Versicolor'}
{'sepal.length': '5.6', 'sepal.width': '3', 'petal.length': '4.5', 'petal.width': '1.5', 'variety': 'Versicolor'}
{'sepal.length': '5.8', 'sepal.width': '2.7', 'petal.length': '4.1', 'petal.width': '1', 'variety': 'Versicolor'}
{'sepal.length': '6.2', 'sepal.width': '2.2', 'petal.length': '4.5', 'petal.width': '1.5', 'variety': 'Versicolor'}
{'sepal.length': '5.6', 'sepal.width': '2.5', 'petal.length': '3.9', 'petal.width': '1.1', 'variety': 'Versicolor'}
{'sepal.length': '5.9', 'sepal.width': '3.2', 'petal.length': '4.8', 'petal.width': '1.8', 'variety': 'Versicolor'}
{'sepal.length': '6.1', 'sepal.width': '2.8', 'petal.length': '4', 'petal.width': '1.3', 'variety': 'Versicolor'}
{'sepal.length': '6.3', 'sepal.width': '2.5', 'petal.length': '4.9', 'petal.width': '1.5', 'variety': 'Versicolor'}
{'sepal.length': '6.1', 'sepal.width': '2.8', 'petal.length': '4.7', 'petal.width': '1.2', 'variety': 'Versicolor'}
{'sepal.length': '6.4', 'sepal.width': '2.9', 'petal.length': '4.3', 'petal.width': '1.3', 'variety': 'Versicolor'}
{'sepal.length': '6.6', 'sepal.width': '3', 'petal.length': '4.4', 'petal.width': '1.4', 'variety': 'Versicolor'}
{'sepal.length': '6.8', 'sepal.width': '2.8', 'petal.length': '4.8', 'petal.width': '1.4', 'variety': 'Versicolor'}
{'sepal.length': '6.7', 'sepal.width': '3', 'petal.length': '5', 'petal.width': '1.7', 'variety': 'Versicolor'}
{'sepal.length': '6', 'sepal.width': '2.9', 'petal.length': '4.5', 'petal.width': '1.5', 'variety': 'Versicolor'}
{'sepal.length': '5.7', 'sepal.width': '2.6', 'petal.length': '3.5', 'petal.width': '1', 'variety': 'Versicolor'}
{'sepal.length': '5.5', 'sepal.width': '2.4', 'petal.length': '3.8', 'petal.width': '1.1', 'variety': 'Versicolor'}
{'sepal.length': '5.5', 'sepal.width': '2.4', 'petal.length': '3.7', 'petal.width': '1', 'variety': 'Versicolor'}
{'sepal.length': '5.8', 'sepal.width': '2.7', 'petal.length': '3.9', 'petal.width': '1.2', 'variety': 'Versicolor'}
{'sepal.length': '6', 'sepal.width': '2.7', 'petal.length': '5.1', 'petal.width': '1.6', 'variety': 'Versicolor'}
{'sepal.length': '5.4', 'sepal.width': '3', 'petal.length': '4.5', 'petal.width': '1.5', 'variety': 'Versicolor'}
{'sepal.length': '6', 'sepal.width': '3.4', 'petal.length': '4.5', 'petal.width': '1.6', 'variety': 'Versicolor'}
{'sepal.length': '6.7', 'sepal.width': '3.1', 'petal.length': '4.7', 'petal.width': '1.5', 'variety': 'Versicolor'}
{'sepal.length': '6.3', 'sepal.width': '2.3', 'petal.length': '4.4', 'petal.width': '1.3', 'variety': 'Versicolor'}
{'sepal.length': '5.6', 'sepal.width': '3', 'petal.length': '4.1', 'petal.width': '1.3', 'variety': 'Versicolor'}
{'sepal.length': '5.5', 'sepal.width': '2.5', 'petal.length': '4', 'petal.width': '1.3', 'variety': 'Versicolor'}
{'sepal.length': '5.5', 'sepal.width': '2.6', 'petal.length': '4.4', 'petal.width': '1.2', 'variety': 'Versicolor'}
{'sepal.length': '6.1', 'sepal.width': '3', 'petal.length': '4.6', 'petal.width': '1.4', 'variety': 'Versicolor'}
{'sepal.length': '5.8', 'sepal.width': '2.6', 'petal.length': '4', 'petal.width': '1.2', 'variety': 'Versicolor'}
{'sepal.length': '5', 'sepal.width': '2.3', 'petal.length': '3.3', 'petal.width': '1', 'variety': 'Versicolor'}
{'sepal.length': '5.6', 'sepal.width': '2.7', 'petal.length': '4.2', 'petal.width': '1.3', 'variety': 'Versicolor'}
{'sepal.length': '5.7', 'sepal.width': '3', 'petal.length': '4.2', 'petal.width': '1.2', 'variety': 'Versicolor'}
{'sepal.length': '5.7', 'sepal.width': '2.9', 'petal.length': '4.2', 'petal.width': '1.3', 'variety': 'Versicolor'}
{'sepal.length': '6.2', 'sepal.width': '2.9', 'petal.length': '4.3', 'petal.width': '1.3', 'variety': 'Versicolor'}
{'sepal.length': '5.1', 'sepal.width': '2.5', 'petal.length': '3', 'petal.width': '1.1', 'variety': 'Versicolor'}
{'sepal.length': '5.7', 'sepal.width': '2.8', 'petal.length': '4.1', 'petal.width': '1.3', 'variety': 'Versicolor'}
{'sepal.length': '6.3', 'sepal.width': '3.3', 'petal.length': '6', 'petal.width': '2.5', 'variety': 'Virginica'}
{'sepal.length': '5.8', 'sepal.width': '2.7', 'petal.length': '5.1', 'petal.width': '1.9', 'variety': 'Virginica'}
{'sepal.length': '7.1', 'sepal.width': '3', 'petal.length': '5.9', 'petal.width': '2.1', 'variety': 'Virginica'}
{'sepal.length': '6.3', 'sepal.width': '2.9', 'petal.length': '5.6', 'petal.width': '1.8', 'variety': 'Virginica'}
{'sepal.length': '6.5', 'sepal.width': '3', 'petal.length': '5.8', 'petal.width': '2.2', 'variety': 'Virginica'}
{'sepal.length': '7.6', 'sepal.width': '3', 'petal.length': '6.6', 'petal.width': '2.1', 'variety': 'Virginica'}
{'sepal.length': '4.9', 'sepal.width': '2.5', 'petal.length': '4.5', 'petal.width': '1.7', 'variety': 'Virginica'}
{'sepal.length': '7.3', 'sepal.width': '2.9', 'petal.length': '6.3', 'petal.width': '1.8', 'variety': 'Virginica'}
{'sepal.length': '6.7', 'sepal.width': '2.5', 'petal.length': '5.8', 'petal.width': '1.8', 'variety': 'Virginica'}
{'sepal.length': '7.2', 'sepal.width': '3.6', 'petal.length': '6.1', 'petal.width': '2.5', 'variety': 'Virginica'}
{'sepal.length': '6.5', 'sepal.width': '3.2', 'petal.length': '5.1', 'petal.width': '2', 'variety': 'Virginica'}
{'sepal.length': '6.4', 'sepal.width': '2.7', 'petal.length': '5.3', 'petal.width': '1.9', 'variety': 'Virginica'}
{'sepal.length': '6.8', 'sepal.width': '3', 'petal.length': '5.5', 'petal.width': '2.1', 'variety': 'Virginica'}
{'sepal.length': '5.7', 'sepal.width': '2.5', 'petal.length': '5', 'petal.width': '2', 'variety': 'Virginica'}
{'sepal.length': '5.8', 'sepal.width': '2.8', 'petal.length': '5.1', 'petal.width': '2.4', 'variety': 'Virginica'}
{'sepal.length': '6.4', 'sepal.width': '3.2', 'petal.length': '5.3', 'petal.width': '2.3', 'variety': 'Virginica'}
{'sepal.length': '6.5', 'sepal.width': '3', 'petal.length': '5.5', 'petal.width': '1.8', 'variety': 'Virginica'}
{'sepal.length': '7.7', 'sepal.width': '3.8', 'petal.length': '6.7', 'petal.width': '2.2', 'variety': 'Virginica'}
{'sepal.length': '7.7', 'sepal.width': '2.6', 'petal.length': '6.9', 'petal.width': '2.3', 'variety': 'Virginica'}
{'sepal.length': '6', 'sepal.width': '2.2', 'petal.length': '5', 'petal.width': '1.5', 'variety': 'Virginica'}
{'sepal.length': '6.9', 'sepal.width': '3.2', 'petal.length': '5.7', 'petal.width': '2.3', 'variety': 'Virginica'}
{'sepal.length': '5.6', 'sepal.width': '2.8', 'petal.length': '4.9', 'petal.width': '2', 'variety': 'Virginica'}
{'sepal.length': '7.7', 'sepal.width': '2.8', 'petal.length': '6.7', 'petal.width': '2', 'variety': 'Virginica'}
{'sepal.length': '6.3', 'sepal.width': '2.7', 'petal.length': '4.9', 'petal.width': '1.8', 'variety': 'Virginica'}
{'sepal.length': '6.7', 'sepal.width': '3.3', 'petal.length': '5.7', 'petal.width': '2.1', 'variety': 'Virginica'}
{'sepal.length': '7.2', 'sepal.width': '3.2', 'petal.length': '6', 'petal.width': '1.8', 'variety': 'Virginica'}
{'sepal.length': '6.2', 'sepal.width': '2.8', 'petal.length': '4.8', 'petal.width': '1.8', 'variety': 'Virginica'}
{'sepal.length': '6.1', 'sepal.width': '3', 'petal.length': '4.9', 'petal.width': '1.8', 'variety': 'Virginica'}
{'sepal.length': '6.4', 'sepal.width': '2.8', 'petal.length': '5.6', 'petal.width': '2.1', 'variety': 'Virginica'}
{'sepal.length': '7.2', 'sepal.width': '3', 'petal.length': '5.8', 'petal.width': '1.6', 'variety': 'Virginica'}
{'sepal.length': '7.4', 'sepal.width': '2.8', 'petal.length': '6.1', 'petal.width': '1.9', 'variety': 'Virginica'}
{'sepal.length': '7.9', 'sepal.width': '3.8', 'petal.length': '6.4', 'petal.width': '2', 'variety': 'Virginica'}
{'sepal.length': '6.4', 'sepal.width': '2.8', 'petal.length': '5.6', 'petal.width': '2.2', 'variety': 'Virginica'}
{'sepal.length': '6.3', 'sepal.width': '2.8', 'petal.length': '5.1', 'petal.width': '1.5', 'variety': 'Virginica'}
{'sepal.length': '6.1', 'sepal.width': '2.6', 'petal.length': '5.6', 'petal.width': '1.4', 'variety': 'Virginica'}
{'sepal.length': '7.7', 'sepal.width': '3', 'petal.length': '6.1', 'petal.width': '2.3', 'variety': 'Virginica'}
{'sepal.length': '6.3', 'sepal.width': '3.4', 'petal.length': '5.6', 'petal.width': '2.4', 'variety': 'Virginica'}
{'sepal.length': '6.4', 'sepal.width': '3.1', 'petal.length': '5.5', 'petal.width': '1.8', 'variety': 'Virginica'}
{'sepal.length': '6', 'sepal.width': '3', 'petal.length': '4.8', 'petal.width': '1.8', 'variety': 'Virginica'}
{'sepal.length': '6.9', 'sepal.width': '3.1', 'petal.length': '5.4', 'petal.width': '2.1', 'variety': 'Virginica'}
{'sepal.length': '6.7', 'sepal.width': '3.1', 'petal.length': '5.6', 'petal.width': '2.4', 'variety': 'Virginica'}
{'sepal.length': '6.9', 'sepal.width': '3.1', 'petal.length': '5.1', 'petal.width': '2.3', 'variety': 'Virginica'}
{'sepal.length': '5.8', 'sepal.width': '2.7', 'petal.length': '5.1', 'petal.width': '1.9', 'variety': 'Virginica'}
{'sepal.length': '6.8', 'sepal.width': '3.2', 'petal.length': '5.9', 'petal.width': '2.3', 'variety': 'Virginica'}
{'sepal.length': '6.7', 'sepal.width': '3.3', 'petal.length': '5.7', 'petal.width': '2.5', 'variety': 'Virginica'}
{'sepal.length': '6.7', 'sepal.width': '3', 'petal.length': '5.2', 'petal.width': '2.3', 'variety': 'Virginica'}
{'sepal.length': '6.3', 'sepal.width': '2.5', 'petal.length': '5', 'petal.width': '1.9', 'variety': 'Virginica'}
{'sepal.length': '6.5', 'sepal.width': '3', 'petal.length': '5.2', 'petal.width': '2', 'variety': 'Virginica'}
{'sepal.length': '6.2', 'sepal.width': '3.4', 'petal.length': '5.4', 'petal.width': '2.3', 'variety': 'Virginica'}
{'sepal.length': '5.9', 'sepal.width': '3', 'petal.length': '5.1', 'petal.width': '1.8', 'variety': 'Virginica'}

In [34]:
import pandas as pd

In [35]:
iris = pd.read_csv("C://data//iris.csv")

In [36]:
iris.head()

   sepal.length  sepal.width  petal.length  petal.width variety
0           5.1          3.5           1.4          0.2  Setosa
1           4.9          3.0           1.4          0.2  Setosa
2           4.7          3.2           1.3          0.2  Setosa
3           4.6          3.1           1.5          0.2  Setosa
4           5.0          3.6           1.4          0.2  Setosa

In [37]:
iris= pd.read_csv("https://gist.githubusercontent.com/netj/8836201/raw/6f9306ad21398ea43cba4f7d537619d0e07d5ae3/iris.csv")

In [38]:
iris

     sepal.length  sepal.width  petal.length  petal.width    variety
0             5.1          3.5           1.4          0.2     Setosa
1             4.9          3.0           1.4          0.2     Setosa
2             4.7          3.2           1.3          0.2     Setosa
3             4.6          3.1           1.5          0.2     Setosa
4             5.0          3.6           1.4          0.2     Setosa
..            ...          ...           ...          ...        ...
145           6.7          3.0           5.2          2.3  Virginica
146           6.3          2.5           5.0          1.9  Virginica
147           6.5          3.0           5.2          2.0  Virginica
148           6.2          3.4           5.4          2.3  Virginica
149           5.9          3.0           5.1          1.8  Virginica

[150 rows x 5 columns]

In [45]:
print(iris.columns)

Index(['sepal.length', 'sepal.width', 'petal.length', 'petal.width',
       'variety'],
      dtype='object')

In [39]:
jsondata = pd.read_json("https://jsonplaceholder.typicode.com/todos")

In [40]:
jsondata.head()

   userId  id                                              title  completed
0       1   1                                 delectus aut autem      False
1       1   2                 quis ut nam facilis et officia qui      False
2       1   3                                fugiat veniam minus      False
3       1   4                                   et porro tempora       True
4       1   5  laboriosam mollitia et enim quasi adipisci qui...      False

In [42]:
xmldata=pd.read_xml("https://www.w3schools.com/xml/cd_catalog.xml")

In [43]:
xmldata

,TITLE,ARTIST,COUNTRY,COMPANY,PRICE,YEAR
0,Empire Burlesque,Bob Dylan,USA,Columbia,10.9,1985
1,Hide your heart,Bonnie Tyler,UK,CBS Records,9.9,1988
2,Greatest Hits,Dolly Parton,USA,RCA,9.9,1982
3,Still got the blues,Gary Moore,UK,Virgin records,10.2,1990
4,Eros,Eros Ramazzotti,EU,BMG,9.9,1997
5,One night only,Bee Gees,UK,Polydor,10.9,1998
6,Sylvias Mother,Dr.Hook,UK,CBS,8.1,1973
7,Maggie May,Rod Stewart,UK,Pickwick,8.5,1990
8,Romanza,Andrea Bocelli,EU,Polydor,10.8,1996
9,When a man loves a woman,Percy Sledge,USA,Atlantic,8.7,1987
10,Black angel,Savage Rose,EU,Mega,10.9,1995
11,1999 Grammy Nominees,Many,USA,Grammy,10.2,1999
12,For the good times,Kenny Rogers,UK,Mucik Master,8.7,1995
13,Big Willie style,Will Smith,USA,Columbia,9.9,1997
14,Tupelo Honey,Van Morrison,UK,Polydor,8.2,1971
15,Soulsville,Jorn Hoel,Norway,WEA,7.9,1996
16,The very best of,Cat Stevens,UK,Island,8.9,1990
17,Stop,Sam Brown,UK,A and M,8.9,1988
18,Bridge of Spies,T'Pau,UK,Siren,7.9,1987
19,Private Dancer,Tina Turner,UK,Capitol,8.9,1983
20,Midt om natten,Kim Larsen,EU,Medley,7.8,1983
21,Pavarotti Gala Concert,Luciano Pavarotti,UK,DECCA,9.9,1991
22,The dock of the bay,Otis Redding,USA,Stax Records,7.9,1968
23,Picture book,Simply Red,EU,Elektra,7.2,1985
24,Red,The Communards,UK,London,7.8,1987
25,Unchain my heart,Joe Cocker,USA,EMI,8.2,1987

In [46]:
xmldata=pd.read_xml("C://data//cd_catalog.xml")

In [47]:
xmldata

,TITLE,ARTIST,COUNTRY,COMPANY,PRICE,YEAR
0,Empire Burlesque,Bob Dylan,USA,Columbia,10.9,1985
1,Hide your heart,Bonnie Tyler,UK,CBS Records,9.9,1988
2,Greatest Hits,Dolly Parton,USA,RCA,9.9,1982
3,Still got the blues,Gary Moore,UK,Virgin records,10.2,1990
4,Eros,Eros Ramazzotti,EU,BMG,9.9,1997
5,One night only,Bee Gees,UK,Polydor,10.9,1998
6,Sylvias Mother,Dr.Hook,UK,CBS,8.1,1973
7,Maggie May,Rod Stewart,UK,Pickwick,8.5,1990
8,Romanza,Andrea Bocelli,EU,Polydor,10.8,1996
9,When a man loves a woman,Percy Sledge,USA,Atlantic,8.7,1987
10,Black angel,Savage Rose,EU,Mega,10.9,1995
11,1999 Grammy Nominees,Many,USA,Grammy,10.2,1999
12,For the good times,Kenny Rogers,UK,Mucik Master,8.7,1995
13,Big Willie style,Will Smith,USA,Columbia,9.9,1997
14,Tupelo Honey,Van Morrison,UK,Polydor,8.2,1971
15,Soulsville,Jorn Hoel,Norway,WEA,7.9,1996
16,The very best of,Cat Stevens,UK,Island,8.9,1990
17,Stop,Sam Brown,UK,A and M,8.9,1988
18,Bridge of Spies,T'Pau,UK,Siren,7.9,1987
19,Private Dancer,Tina Turner,UK,Capitol,8.9,1983
20,Midt om natten,Kim Larsen,EU,Medley,7.8,1983
21,Pavarotti Gala Concert,Luciano Pavarotti,UK,DECCA,9.9,1991
22,The dock of the bay,Otis Redding,USA,Stax Records,7.9,1968
23,Picture book,Simply Red,EU,Elektra,7.2,1985
24,Red,The Communards,UK,London,7.8,1987
25,Unchain my heart,Joe Cocker,USA,EMI,8.2,1987

In [49]:
xmldata.to_csv("C://data//xmldata.csv",index=False)

In [50]:
help(xmldata.to_csv)

Help on method to_csv in module pandas.core.generic:

to_csv(path_or_buf: 'FilePathOrBuffer[AnyStr] | None' = None, sep: 'str' = ',', na_rep: 'str' = '', float_format: 'str | None' = None, columns: 'Sequence[Hashable] | None' = None, header: 'bool_t | list[str]' = True, index: 'bool_t' = True, index_label: 'IndexLabel | None' = None, mode: 'str' = 'w', encoding: 'str | None' = None, compression: 'CompressionOptions' = 'infer', quoting: 'int | None' = None, quotechar: 'str' = '"', line_terminator: 'str | None' = None, chunksize: 'int | None' = None, date_format: 'str | None' = None, doublequote: 'bool_t' = True, escapechar: 'str | None' = None, decimal: 'str' = '.', errors: 'str' = 'strict', storage_options: 'StorageOptions' = None) -> 'str | None' method of pandas.core.frame.DataFrame instance
    Write object to a comma-separated values (csv) file.

    Parameters
    ----------
    path_or_buf : str or file handle, default None
        File path or object, if None is provided the result is returned as
        a string.  If a non-binary file object is passed, it should be opened
        with `newline=''`, disabling universal newlines. If a binary
        file object is passed, `mode` might need to contain a `'b'`.

        .. versionchanged:: 1.2.0

           Support for binary file objects was introduced.

    sep : str, default ','
        String of length 1. Field delimiter for the output file.
    na_rep : str, default ''
        Missing data representation.
    float_format : str, default None
        Format string for floating point numbers.
    columns : sequence, optional
        Columns to write.
    header : bool or list of str, default True
        Write out the column names. If a list of strings is given it is
        assumed to be aliases for the column names.
    index : bool, default True
        Write row names (index).
    index_label : str or sequence, or False, default None
        Column label for index column(s) if desired. If None is given, and
        `header` and `index` are True, then the index names are used. A
        sequence should be given if the object uses MultiIndex. If
        False do not print fields for index names. Use index_label=False
        for easier importing in R.
    mode : str
        Python write mode, default 'w'.
    encoding : str, optional
        A string representing the encoding to use in the output file,
        defaults to 'utf-8'. `encoding` is not supported if `path_or_buf`
        is a non-binary file object.
    compression : str or dict, default 'infer'
        If str, represents compression mode. If dict, value at 'method' is
        the compression mode. Compression mode may be any of the following
        possible values: {'infer', 'gzip', 'bz2', 'zip', 'xz', None}. If
        compression mode is 'infer' and `path_or_buf` is path-like, then
        detect compression mode from the following extensions: '.gz',
        '.bz2', '.zip' or '.xz'. (otherwise no compression). If dict given
        and mode is one of {'zip', 'gzip', 'bz2'}, or inferred as
        one of the above, other entries passed as
        additional compression options.

        .. versionchanged:: 1.0.0

           May now be a dict with key 'method' as compression mode
           and other entries as additional compression options if
           compression mode is 'zip'.

        .. versionchanged:: 1.1.0

           Passing compression options as keys in dict is
           supported for compression modes 'gzip' and 'bz2'
           as well as 'zip'.

        .. versionchanged:: 1.2.0

            Compression is supported for binary file objects.

        .. versionchanged:: 1.2.0

            Previous versions forwarded dict entries for 'gzip' to
            `gzip.open` instead of `gzip.GzipFile` which prevented
            setting `mtime`.

    quoting : optional constant from csv module
        Defaults to csv.QUOTE_MINIMAL. If you have set a `float_format`
        then floats are converted to strings and thus csv.QUOTE_NONNUMERIC
        will treat them as non-numeric.
    quotechar : str, default '\"'
        String of length 1. Character used to quote fields.
    line_terminator : str, optional
        The newline character or character sequence to use in the output
        file. Defaults to `os.linesep`, which depends on the OS in which
        this method is called ('\\n' for linux, '\\r\\n' for Windows, i.e.).
    chunksize : int or None
        Rows to write at a time.
    date_format : str, default None
        Format string for datetime objects.
    doublequote : bool, default True
        Control quoting of `quotechar` inside a field.
    escapechar : str, default None
        String of length 1. Character used to escape `sep` and `quotechar`
        when appropriate.
    decimal : str, default '.'
        Character recognized as decimal separator. E.g. use ',' for
        European data.
    errors : str, default 'strict'
        Specifies how encoding and decoding errors are to be handled.
        See the errors argument for :func:`open` for a full list
        of options.

        .. versionadded:: 1.1.0

    storage_options : dict, optional
        Extra options that make sense for a particular storage connection, e.g.
        host, port, username, password, etc. For HTTP(S) URLs the key-value pairs
        are forwarded to ``urllib`` as header options. For other URLs (e.g.
        starting with "s3://", and "gcs://") the key-value pairs are forwarded to
        ``fsspec``. Please see ``fsspec`` and ``urllib`` for more details.

        .. versionadded:: 1.2.0

    Returns
    -------
    None or str
        If path_or_buf is None, returns the resulting csv format as a
        string. Otherwise returns None.

    See Also
    --------
    read_csv : Load a CSV file into a DataFrame.
    to_excel : Write DataFrame to an Excel file.

    Examples
    --------
    >>> df = pd.DataFrame({'name': ['Raphael', 'Donatello'],
    ...                    'mask': ['red', 'purple'],
    ...                    'weapon': ['sai', 'bo staff']})
    >>> df.to_csv(index=False)
    'name,mask,weapon\nRaphael,red,sai\nDonatello,purple,bo staff\n'

    Create 'out.zip' containing 'out.csv'

    >>> compression_opts = dict(method='zip',
    ...                         archive_name='out.csv')  # doctest: +SKIP
    >>> df.to_csv('out.zip', index=False,
    ...           compression=compression_opts)  # doctest: +SKIP

In [51]:
jsondata.to_csv("C://data//jsondata.csv")

In [52]:
jsondata.to_excel("C://data//jsondata.xlsx")

In [53]:
help(pd.read_sql)

Help on function read_sql in module pandas.io.sql:

read_sql(sql, con, index_col: 'str | Sequence[str] | None' = None, coerce_float: 'bool' = True, params=None, parse_dates=None, columns=None, chunksize: 'int | None' = None) -> 'DataFrame | Iterator[DataFrame]'
    Read SQL query or database table into a DataFrame.

    This function is a convenience wrapper around ``read_sql_table`` and
    ``read_sql_query`` (for backward compatibility). It will delegate
    to the specific function depending on the provided input. A SQL query
    will be routed to ``read_sql_query``, while a database table name will
    be routed to ``read_sql_table``. Note that the delegated function might
    have more specific notes about their functionality not listed here.

    Parameters
    ----------
    sql : str or SQLAlchemy Selectable (select or text object)
        SQL query to be executed or a table name.
    con : SQLAlchemy connectable, str, or sqlite3 connection
        Using SQLAlchemy makes it possible to use any DB supported by that
        library. If a DBAPI2 object, only sqlite3 is supported. The user is responsible
        for engine disposal and connection closure for the SQLAlchemy connectable; str
        connections are closed automatically. See
        `here <https://docs.sqlalchemy.org/en/13/core/connections.html>`_.
    index_col : str or list of str, optional, default: None
        Column(s) to set as index(MultiIndex).
    coerce_float : bool, default True
        Attempts to convert values of non-string, non-numeric objects (like
        decimal.Decimal) to floating point, useful for SQL result sets.
    params : list, tuple or dict, optional, default: None
        List of parameters to pass to execute method.  The syntax used
        to pass parameters is database driver dependent. Check your
        database driver documentation for which of the five syntax styles,
        described in PEP 249's paramstyle, is supported.
        Eg. for psycopg2, uses %(name)s so use params={'name' : 'value'}.
    parse_dates : list or dict, default: None
        - List of column names to parse as dates.
        - Dict of ``{column_name: format string}`` where format string is
          strftime compatible in case of parsing string times, or is one of
          (D, s, ns, ms, us) in case of parsing integer timestamps.
        - Dict of ``{column_name: arg dict}``, where the arg dict corresponds
          to the keyword arguments of :func:`pandas.to_datetime`
          Especially useful with databases without native Datetime support,
          such as SQLite.
    columns : list, default: None
        List of column names to select from SQL table (only used when reading
        a table).
    chunksize : int, default None
        If specified, return an iterator where `chunksize` is the
        number of rows to include in each chunk.

    Returns
    -------
    DataFrame or Iterator[DataFrame]

    See Also
    --------
    read_sql_table : Read SQL database table into a DataFrame.
    read_sql_query : Read SQL query into a DataFrame.

    Examples
    --------
    Read data from SQL via either a SQL query or a SQL tablename.
    When using a SQLite database only SQL queries are accepted,
    providing only the SQL tablename will result in an error.

    >>> from sqlite3 import connect
    >>> conn = connect(':memory:')
    >>> df = pd.DataFrame(data=[[0, '10/11/12'], [1, '12/11/10']],
    ...                   columns=['int_column', 'date_column'])
    >>> df.to_sql('test_data', conn)

    >>> pd.read_sql('SELECT int_column, date_column FROM test_data', conn)
       int_column date_column
    0           0    10/11/12
    1           1    12/11/10

    >>> pd.read_sql('test_data', 'postgres:///db_name')  # doctest:+SKIP

    Apply date parsing to columns through the ``parse_dates`` argument

    >>> pd.read_sql('SELECT int_column, date_column FROM test_data',
    ...             conn,
    ...             parse_dates=["date_column"])
       int_column date_column
    0           0  2012-10-11
    1           1  2010-12-11

    The ``parse_dates`` argument calls ``pd.to_datetime`` on the provided columns.
    Custom argument values for applying ``pd.to_datetime`` on a column are specified
    via a dictionary format:
    1. Ignore errors while parsing the values of "date_column"

    >>> pd.read_sql('SELECT int_column, date_column FROM test_data',
    ...             conn,
    ...             parse_dates={"date_column": {"errors": "ignore"}})
       int_column date_column
    0           0  2012-10-11
    1           1  2010-12-11

    2. Apply a dayfirst date parsing order on the values of "date_column"

    >>> pd.read_sql('SELECT int_column, date_column FROM test_data',
    ...             conn,
    ...             parse_dates={"date_column": {"dayfirst": True}})
       int_column date_column
    0           0  2012-11-10
    1           1  2010-11-12

    3. Apply custom formatting when date parsing the values of "date_column"

    >>> pd.read_sql('SELECT int_column, date_column FROM test_data',
    ...             conn,
    ...             parse_dates={"date_column": {"format": "%d/%m/%y"}})
       int_column date_column
    0           0  2012-11-10
    1           1  2010-11-12